package org.openinfobutton.service.dao;

/*
 * #%L
 * Project:  oib-app-service
 * Director: Guilherme Del Fiol, MD, PhD
 *           University of Utah
 *           Biomedical Informatics
 *           421 Wakara Way, Suite 140
 *           Salt Lake City, UT 84108-3514
 * Phone:    801-581-4080
 * %%
 * Copyright (C) 2010 - 2014 University of Utah
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */
import java.math.BigDecimal;
import java.util.List;
import java.util.Set;
import org.openinfobutton.app.dao.AssetDaoI;
import org.openinfobutton.app.model.Asset;
import org.openinfobutton.app.model.AssetProperty;

/**
 * The Interface ServiceAssetDao.
 *
 * @author rick
 */
public interface ServiceAssetDao
        extends AssetDaoI {

    /**
     * Find max asset property group.
     *
     * @param assetId the asset id
     * @return the int
     */
    public int findMaxAssetPropertyGroup(BigDecimal assetId);

    /**
     * Find assets by property code system.
     *
     * @param codeSystem the code system
     * @return the list
     */
    public List<Asset> findAssetsByPropertyCodeSystem(String codeSystem);

    /**
     * Adds the asset property.
     *
     * @param assetProperty the asset property
     */
    public void addAssetProperty(AssetProperty assetProperty);

    /**
     * Delete all asset properties by generated by code.
     *
     * @param generatedByCodes the generated by codes
     */
    public void deleteAllAssetPropertiesByGeneratedByCode(Set<String> generatedByCodes);

    /**
     * Delete all asset properties by generated by code and code system.
     *
     * @param codeSystem the code system
     * @param generatedByCode the generated by code
     */
    public void deleteAllAssetPropertiesByGeneratedByCodeAndCodeSystem(String codeSystem, String generatedByCode);

    /**
     * Delete asset properties by generated by code.
     *
     * @param assetId the asset id
     * @param generatedByCode the generated by code
     */
    public void deleteAssetPropertiesByGeneratedByCode(BigDecimal assetId, String generatedByCode);

    /**
     * Delete asset properties by generated by code and code system.
     *
     * @param assetId the asset id
     * @param codeSystem the code system
     * @param generatedByCode the generated by code
     */
    public void deleteAssetPropertiesByGeneratedByCodeAndCodeSystem(BigDecimal assetId, String codeSystem,
            String generatedByCode);

}
