package org.openinfobutton.app.model;

/*
 * #%L
 * Project:  oib-app-model
 * Director: Guilherme Del Fiol, MD, PhD
 *           University of Utah
 *           Biomedical Informatics
 *           421 Wakara Way, Suite 140
 *           Salt Lake City, UT 84108-3514
 * Phone:    801-581-4080
 * %%
 * Copyright (C) 2010 - 2014 University of Utah
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

import com.fasterxml.jackson.annotation.JsonIgnore;

import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Objects;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * The Class AssetProperty.
 *
 * @author rick
 */
@Entity
@Table(name = "OIB_ASSET_PROPERTY")
@XmlRootElement
public class AssetProperty
        implements Serializable, Cloneable {

    /**
     * The Constant serialVersionUID.
     */
    private static final long serialVersionUID = 1L;

    /**
     * The asset property id.
     */
    @Id
    @SequenceGenerator(name = "objectIdSequence2", sequenceName = "OIB_ID_SEQ")
    @GeneratedValue(strategy = GenerationType.AUTO, generator = "objectIdSequence2")
    @Basic(optional = false)
    @Column(name = "ASSET_PROPERTY_ID")
    private BigDecimal assetPropertyId;

    /**
     * The property group number.
     */
    @Column(name = "PROP_GROUP_NUM")
    private BigInteger propertyGroupNumber;

    /**
     * The property name.
     */
    @Column(name = "PROP_NAME")
    private String propertyName;

    /**
     * The property type.
     */
    @Column(name = "PROP_TYPE_CD")
    private String propertyType;

    /**
     * The code.
     */
    @Column(name = "CODE")
    private String code;

    /**
     * The code system.
     */
    @Column(name = "CODE_SYSTEM")
    private String codeSystem;

    /**
     * The display name.
     */
    @Column(name = "DISPLAY_NAME")
    private String displayName;

    /**
     * The property value.
     */
    @Column(name = "PROP_VALUE")
    private String propertyValue;

    /**
     * The generated by code.
     */
    @Column(name = "GENERATED_BY_CD")
    private String generatedByCode;

    /**
     * The asset.
     */
    @JoinColumn(name = "ASSET_ID", referencedColumnName = "ASSET_ID")
    @ManyToOne
    private Asset asset;

    /**
     * Instantiates a new asset property.
     */
    public AssetProperty() {
    }

    /**
     * Instantiates a new asset property.
     *
     * @param assetPropertyId the asset property id
     */
    public AssetProperty(BigDecimal assetPropertyId) {
        this.assetPropertyId = assetPropertyId;
    }

    /**
     * Gets the asset property id.
     *
     * @return the asset property id
     */
    public BigDecimal getAssetPropertyId() {
        return assetPropertyId;
    }

    /**
     * Sets the asset property id.
     *
     * @param assetPropertyId the new asset property id
     */
    public void setAssetPropertyId(BigDecimal assetPropertyId) {
        this.assetPropertyId = assetPropertyId;
    }

    /**
     * Gets the property group number.
     *
     * @return the property group number
     */
    public BigInteger getPropertyGroupNumber() {
        return propertyGroupNumber;
    }

    /**
     * Sets the property group number.
     *
     * @param propertyGroupNumber the new property group number
     */
    public void setPropertyGroupNumber(BigInteger propertyGroupNumber) {
        this.propertyGroupNumber = propertyGroupNumber;
    }

    /**
     * Gets the property name.
     *
     * @return the property name
     */
    public String getPropertyName() {
        return propertyName;
    }

    /**
     * Sets the property name.
     *
     * @param propertyName the new property name
     */
    public void setPropertyName(String propertyName) {
        this.propertyName = propertyName;
    }

    /**
     * Gets the property type.
     *
     * @return the property type
     */
    public String getPropertyType() {
        return propertyType;
    }

    /**
     * Sets the property type.
     *
     * @param propertyType the new property type
     */
    public void setPropertyType(String propertyType) {
        this.propertyType = propertyType;
    }

    /**
     * Gets the code.
     *
     * @return the code
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the code.
     *
     * @param code the new code
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * Gets the code system.
     *
     * @return the code system
     */
    public String getCodeSystem() {
        return codeSystem;
    }

    /**
     * Sets the code system.
     *
     * @param codeSystem the new code system
     */
    public void setCodeSystem(String codeSystem) {
        this.codeSystem = codeSystem;
    }

    /**
     * Gets the display name.
     *
     * @return the display name
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Sets the display name.
     *
     * @param displayName the new display name
     */
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    /**
     * Gets the property value.
     *
     * @return the property value
     */
    public String getPropertyValue() {
        return propertyValue;
    }

    /**
     * Sets the property value.
     *
     * @param propertyValue the new property value
     */
    public void setPropertyValue(String propertyValue) {
        this.propertyValue = propertyValue;
    }

    /**
     * Gets the asset.
     *
     * @return the asset
     */
    public Asset getAsset() {
        return asset;
    }

    /**
     * Sets the asset.
     *
     * @param asset the new asset
     */
    public void setAsset(Asset asset) {
        this.asset = asset;
    }

    /**
     * Sets the generated by code.
     *
     * @param generatedByCode the new generated by code
     */
    public void setGeneratedByCode(String generatedByCode) {
        this.generatedByCode = generatedByCode;
    }

    /**
     * Gets the generated by code.
     *
     * @return the generated by code
     */
    public String getGeneratedByCode() {
        return generatedByCode;
    }

    /*
     * (non-Javadoc)
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode() {
        int hash = 0;
        hash += (assetPropertyId != null ? assetPropertyId.hashCode() : 0);
        return hash;
    }

    /*
     * (non-Javadoc)
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof AssetProperty)) {
            return false;
        }
        final AssetProperty other = (AssetProperty) object;
        if ((this.assetPropertyId == null && other.assetPropertyId != null)
                || (this.assetPropertyId != null && !this.assetPropertyId.equals(other.assetPropertyId))) {
            return false;
        }
        return true;
    }

    /*
     * (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return "org.openinfobutton.app.model.AssetProperty[ assetPropertyId=" + assetPropertyId + " ]";
    }

    @Override
    public Object clone() {

        AssetProperty property = new AssetProperty();
        property.setPropertyGroupNumber(this.propertyGroupNumber);
        property.setPropertyName(this.propertyName);
        property.setPropertyType(this.propertyType);
        property.setCode(this.code);
        property.setCodeSystem(this.codeSystem);
        property.setDisplayName(this.displayName);
        property.setPropertyValue(this.propertyValue);
        property.setGeneratedByCode(this.generatedByCode);
        return property;
    }
}
