
package gov.nih.nlm.uts.webservice.history;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UtsWsHistoryController", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UtsWsHistoryController {


    /**
     * 
     * @param ticket
     * @param atomId
     * @param version
     * @return
     *     returns java.util.List<gov.nih.nlm.uts.webservice.history.AtomMovementDTO>
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAtomMovements", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.history.GetAtomMovements")
    @ResponseWrapper(localName = "getAtomMovementsResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.history.GetAtomMovementsResponse")
    public List<AtomMovementDTO> getAtomMovements(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "atomId", targetNamespace = "")
        String atomId)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @param conceptId
     * @param targetVersion
     * @param version
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBequeathedToConceptCuis", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.history.GetBequeathedToConceptCuis")
    @ResponseWrapper(localName = "getBequeathedToConceptCuisResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.history.GetBequeathedToConceptCuisResponse")
    public List<String> getBequeathedToConceptCuis(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "conceptId", targetNamespace = "")
        String conceptId,
        @WebParam(name = "targetVersion", targetNamespace = "")
        String targetVersion)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @param olderVersion
     * @param conceptId
     * @param newerVersion
     * @return
     *     returns java.util.List<gov.nih.nlm.uts.webservice.history.ConceptBequeathalDTO>
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getConceptBequeathals", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.history.GetConceptBequeathals")
    @ResponseWrapper(localName = "getConceptBequeathalsResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.history.GetConceptBequeathalsResponse")
    public List<ConceptBequeathalDTO> getConceptBequeathals(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "newerVersion", targetNamespace = "")
        String newerVersion,
        @WebParam(name = "conceptId", targetNamespace = "")
        String conceptId,
        @WebParam(name = "olderVersion", targetNamespace = "")
        String olderVersion)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @param olderVersion
     * @param conceptId
     * @param newerVersion
     * @return
     *     returns java.util.List<gov.nih.nlm.uts.webservice.history.ConceptDeathDTO>
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getConceptDeletions", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.history.GetConceptDeletions")
    @ResponseWrapper(localName = "getConceptDeletionsResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.history.GetConceptDeletionsResponse")
    public List<ConceptDeathDTO> getConceptDeletions(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "newerVersion", targetNamespace = "")
        String newerVersion,
        @WebParam(name = "conceptId", targetNamespace = "")
        String conceptId,
        @WebParam(name = "olderVersion", targetNamespace = "")
        String olderVersion)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @param olderVersion
     * @param conceptId
     * @param newerVersion
     * @return
     *     returns java.util.List<gov.nih.nlm.uts.webservice.history.ConceptMergeDTO>
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getConceptMerges", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.history.GetConceptMerges")
    @ResponseWrapper(localName = "getConceptMergesResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.history.GetConceptMergesResponse")
    public List<ConceptMergeDTO> getConceptMerges(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "newerVersion", targetNamespace = "")
        String newerVersion,
        @WebParam(name = "conceptId", targetNamespace = "")
        String conceptId,
        @WebParam(name = "olderVersion", targetNamespace = "")
        String olderVersion)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @param termId
     * @param version
     * @return
     *     returns java.util.List<gov.nih.nlm.uts.webservice.history.TermMergeDTO>
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTermMerges", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.history.GetTermMerges")
    @ResponseWrapper(localName = "getTermMergesResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.history.GetTermMergesResponse")
    public List<TermMergeDTO> getTermMerges(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "termId", targetNamespace = "")
        String termId)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @param conceptId
     * @param version
     * @return
     *     returns java.lang.String
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMergedToConceptCui", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.history.GetMergedToConceptCui")
    @ResponseWrapper(localName = "getMergedToConceptCuiResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.history.GetMergedToConceptCuiResponse")
    public String getMergedToConceptCui(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "conceptId", targetNamespace = "")
        String conceptId)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @param termId
     * @param version
     * @return
     *     returns java.lang.String
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMergedToTermUi", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.history.GetMergedToTermUi")
    @ResponseWrapper(localName = "getMergedToTermUiResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.history.GetMergedToTermUiResponse")
    public String getMergedToTermUi(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "termId", targetNamespace = "")
        String termId)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @param atomId
     * @param version
     * @return
     *     returns java.lang.String
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMovedToConceptCui", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.history.GetMovedToConceptCui")
    @ResponseWrapper(localName = "getMovedToConceptCuiResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.history.GetMovedToConceptCuiResponse")
    public String getMovedToConceptCui(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "atomId", targetNamespace = "")
        String atomId)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @param conceptId
     * @param sourceAtomId
     * @param rootSourceAbbreviation
     * @param version
     * @return
     *     returns java.util.List<gov.nih.nlm.uts.webservice.history.SourceAtomChangeDTO>
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSourceAtomChanges", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.history.GetSourceAtomChanges")
    @ResponseWrapper(localName = "getSourceAtomChangesResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.history.GetSourceAtomChangesResponse")
    public List<SourceAtomChangeDTO> getSourceAtomChanges(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "conceptId", targetNamespace = "")
        String conceptId,
        @WebParam(name = "rootSourceAbbreviation", targetNamespace = "")
        String rootSourceAbbreviation,
        @WebParam(name = "sourceAtomId", targetNamespace = "")
        String sourceAtomId)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @param fromVersion
     * @param termId
     * @param version
     * @return
     *     returns java.util.List<gov.nih.nlm.uts.webservice.history.TermDeathDTO>
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTermDeletions", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.history.GetTermDeletions")
    @ResponseWrapper(localName = "getTermDeletionsResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.history.GetTermDeletionsResponse")
    public List<TermDeathDTO> getTermDeletions(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "termId", targetNamespace = "")
        String termId,
        @WebParam(name = "fromVersion", targetNamespace = "")
        String fromVersion)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @param fromVersion
     * @param termStringId
     * @param version
     * @return
     *     returns java.util.List<gov.nih.nlm.uts.webservice.history.TermStringDeathDTO>
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTermStringDeletions", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.history.GetTermStringDeletions")
    @ResponseWrapper(localName = "getTermStringDeletionsResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.history.GetTermStringDeletionsResponse")
    public List<TermStringDeathDTO> getTermStringDeletions(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "termStringId", targetNamespace = "")
        String termStringId,
        @WebParam(name = "fromVersion", targetNamespace = "")
        String fromVersion)
        throws UtsFault_Exception
    ;

}
