USE OIB;

ALTER TABLE OIB_ASSET MODIFY ASSET_ID BIGINT AUTO_INCREMENT;

ALTER TABLE OIB_ASSET_PROPERTY MODIFY ASSET_PROPERTY_ID BIGINT AUTO_INCREMENT;

UPDATE OIB_APP_PROPERTY set PROP_NAME = 'uts.username' WHERE APP_PROPERTY_ID = 3146;

UPDATE OIB_APP_PROPERTY set PROP_NAME = 'uts.password' WHERE APP_PROPERTY_ID = 3147;

UPDATE OIB_APP_PROPERTY set PROP_NAME = 'uts.umlsRelease' WHERE APP_PROPERTY_ID = 3148;

UPDATE OIB_APP_PROPERTY set PROP_NAME = 'uts.serviceName' WHERE APP_PROPERTY_ID = 3149;