//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.25 at 09:30:02 AM MST 
//


package edu.duke.mc.cfm.dci.infobutton.schemas.kb;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="header">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="title" type="{}ST"/>
 *                   &lt;element name="profileDescription" type="{}ST"/>
 *                   &lt;element name="versionControl">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="publicationDate" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="profileDefinition">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="authorizedOrganizations">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="authorizedOrganization" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;extension base="{}Id">
 *                                     &lt;sequence>
 *                                       &lt;element name="accessMethod" maxOccurs="unbounded" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="networkAccessMethod" type="{}CD" minOccurs="0"/>
 *                                                 &lt;element name="authenticationMethod">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;choice>
 *                                                           &lt;element name="ip">
 *                                                             &lt;complexType>
 *                                                               &lt;complexContent>
 *                                                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                                   &lt;sequence>
 *                                                                     &lt;element name="ipRange" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded"/>
 *                                                                   &lt;/sequence>
 *                                                                 &lt;/restriction>
 *                                                               &lt;/complexContent>
 *                                                             &lt;/complexType>
 *                                                           &lt;/element>
 *                                                           &lt;element name="usrPwd">
 *                                                             &lt;complexType>
 *                                                               &lt;complexContent>
 *                                                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                                   &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                                                                   &lt;attribute name="certificateText" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                                                                 &lt;/restriction>
 *                                                               &lt;/complexContent>
 *                                                             &lt;/complexType>
 *                                                           &lt;/element>
 *                                                         &lt;/choice>
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/extension>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="supportedTerminologies" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="supportedTerminology" type="{}Id" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="contexts">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="context" type="{}Context" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="hl7URLCompliant" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                 &lt;attribute name="hl7KnowledgeResponseCompliant" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                 &lt;attribute name="urlStyle">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;enumeration value="DIRTY"/>
 *                       &lt;enumeration value="CLEAN"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "header",
    "profileDefinition"
})
@XmlRootElement(name = "knowledgeResourceProfile")
public class KnowledgeResourceProfile {

    @XmlElement(required = true)
    protected KnowledgeResourceProfile.Header header;
    @XmlElement(required = true)
    protected KnowledgeResourceProfile.ProfileDefinition profileDefinition;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link KnowledgeResourceProfile.Header }
     *     
     */
    public KnowledgeResourceProfile.Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link KnowledgeResourceProfile.Header }
     *     
     */
    public void setHeader(KnowledgeResourceProfile.Header value) {
        this.header = value;
    }

    /**
     * Gets the value of the profileDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link KnowledgeResourceProfile.ProfileDefinition }
     *     
     */
    public KnowledgeResourceProfile.ProfileDefinition getProfileDefinition() {
        return profileDefinition;
    }

    /**
     * Sets the value of the profileDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link KnowledgeResourceProfile.ProfileDefinition }
     *     
     */
    public void setProfileDefinition(KnowledgeResourceProfile.ProfileDefinition value) {
        this.profileDefinition = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="title" type="{}ST"/>
     *         &lt;element name="profileDescription" type="{}ST"/>
     *         &lt;element name="versionControl">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="publicationDate" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "title",
        "profileDescription",
        "versionControl"
    })
    public static class Header {

        @XmlElement(required = true)
        protected String title;
        @XmlElement(required = true)
        protected String profileDescription;
        @XmlElement(required = true)
        protected KnowledgeResourceProfile.Header.VersionControl versionControl;
        @XmlAttribute(required = true)
        protected BigInteger id;

        /**
         * Gets the value of the title property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTitle() {
            return title;
        }

        /**
         * Sets the value of the title property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTitle(String value) {
            this.title = value;
        }

        /**
         * Gets the value of the profileDescription property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProfileDescription() {
            return profileDescription;
        }

        /**
         * Sets the value of the profileDescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProfileDescription(String value) {
            this.profileDescription = value;
        }

        /**
         * Gets the value of the versionControl property.
         * 
         * @return
         *     possible object is
         *     {@link KnowledgeResourceProfile.Header.VersionControl }
         *     
         */
        public KnowledgeResourceProfile.Header.VersionControl getVersionControl() {
            return versionControl;
        }

        /**
         * Sets the value of the versionControl property.
         * 
         * @param value
         *     allowed object is
         *     {@link KnowledgeResourceProfile.Header.VersionControl }
         *     
         */
        public void setVersionControl(KnowledgeResourceProfile.Header.VersionControl value) {
            this.versionControl = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setId(BigInteger value) {
            this.id = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="publicationDate" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class VersionControl {

            @XmlAttribute(required = true)
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar publicationDate;

            /**
             * Gets the value of the publicationDate property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getPublicationDate() {
                return publicationDate;
            }

            /**
             * Sets the value of the publicationDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setPublicationDate(XMLGregorianCalendar value) {
                this.publicationDate = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="authorizedOrganizations">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="authorizedOrganization" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;extension base="{}Id">
     *                           &lt;sequence>
     *                             &lt;element name="accessMethod" maxOccurs="unbounded" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="networkAccessMethod" type="{}CD" minOccurs="0"/>
     *                                       &lt;element name="authenticationMethod">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;choice>
     *                                                 &lt;element name="ip">
     *                                                   &lt;complexType>
     *                                                     &lt;complexContent>
     *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                                         &lt;sequence>
     *                                                           &lt;element name="ipRange" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded"/>
     *                                                         &lt;/sequence>
     *                                                       &lt;/restriction>
     *                                                     &lt;/complexContent>
     *                                                   &lt;/complexType>
     *                                                 &lt;/element>
     *                                                 &lt;element name="usrPwd">
     *                                                   &lt;complexType>
     *                                                     &lt;complexContent>
     *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                                         &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *                                                         &lt;attribute name="certificateText" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *                                                       &lt;/restriction>
     *                                                     &lt;/complexContent>
     *                                                   &lt;/complexType>
     *                                                 &lt;/element>
     *                                               &lt;/choice>
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/extension>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="supportedTerminologies" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="supportedTerminology" type="{}Id" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="contexts">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="context" type="{}Context" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="hl7URLCompliant" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *       &lt;attribute name="hl7KnowledgeResponseCompliant" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *       &lt;attribute name="urlStyle">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="DIRTY"/>
     *             &lt;enumeration value="CLEAN"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "authorizedOrganizations",
        "supportedTerminologies",
        "contexts"
    })
    public static class ProfileDefinition {

        @XmlElement(required = true)
        protected KnowledgeResourceProfile.ProfileDefinition.AuthorizedOrganizations authorizedOrganizations;
        protected KnowledgeResourceProfile.ProfileDefinition.SupportedTerminologies supportedTerminologies;
        @XmlElement(required = true)
        protected KnowledgeResourceProfile.ProfileDefinition.Contexts contexts;
        @XmlAttribute(required = true)
        protected boolean hl7URLCompliant;
        @XmlAttribute(required = true)
        protected boolean hl7KnowledgeResponseCompliant;
        @XmlAttribute
        protected String urlStyle;

        /**
         * Gets the value of the authorizedOrganizations property.
         * 
         * @return
         *     possible object is
         *     {@link KnowledgeResourceProfile.ProfileDefinition.AuthorizedOrganizations }
         *     
         */
        public KnowledgeResourceProfile.ProfileDefinition.AuthorizedOrganizations getAuthorizedOrganizations() {
            return authorizedOrganizations;
        }

        /**
         * Sets the value of the authorizedOrganizations property.
         * 
         * @param value
         *     allowed object is
         *     {@link KnowledgeResourceProfile.ProfileDefinition.AuthorizedOrganizations }
         *     
         */
        public void setAuthorizedOrganizations(KnowledgeResourceProfile.ProfileDefinition.AuthorizedOrganizations value) {
            this.authorizedOrganizations = value;
        }

        /**
         * Gets the value of the supportedTerminologies property.
         * 
         * @return
         *     possible object is
         *     {@link KnowledgeResourceProfile.ProfileDefinition.SupportedTerminologies }
         *     
         */
        public KnowledgeResourceProfile.ProfileDefinition.SupportedTerminologies getSupportedTerminologies() {
            return supportedTerminologies;
        }

        /**
         * Sets the value of the supportedTerminologies property.
         * 
         * @param value
         *     allowed object is
         *     {@link KnowledgeResourceProfile.ProfileDefinition.SupportedTerminologies }
         *     
         */
        public void setSupportedTerminologies(KnowledgeResourceProfile.ProfileDefinition.SupportedTerminologies value) {
            this.supportedTerminologies = value;
        }

        /**
         * Gets the value of the contexts property.
         * 
         * @return
         *     possible object is
         *     {@link KnowledgeResourceProfile.ProfileDefinition.Contexts }
         *     
         */
        public KnowledgeResourceProfile.ProfileDefinition.Contexts getContexts() {
            return contexts;
        }

        /**
         * Sets the value of the contexts property.
         * 
         * @param value
         *     allowed object is
         *     {@link KnowledgeResourceProfile.ProfileDefinition.Contexts }
         *     
         */
        public void setContexts(KnowledgeResourceProfile.ProfileDefinition.Contexts value) {
            this.contexts = value;
        }

        /**
         * Gets the value of the hl7URLCompliant property.
         * 
         */
        public boolean isHl7URLCompliant() {
            return hl7URLCompliant;
        }

        /**
         * Sets the value of the hl7URLCompliant property.
         * 
         */
        public void setHl7URLCompliant(boolean value) {
            this.hl7URLCompliant = value;
        }

        /**
         * Gets the value of the hl7KnowledgeResponseCompliant property.
         * 
         */
        public boolean isHl7KnowledgeResponseCompliant() {
            return hl7KnowledgeResponseCompliant;
        }

        /**
         * Sets the value of the hl7KnowledgeResponseCompliant property.
         * 
         */
        public void setHl7KnowledgeResponseCompliant(boolean value) {
            this.hl7KnowledgeResponseCompliant = value;
        }

        /**
         * Gets the value of the urlStyle property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUrlStyle() {
            return urlStyle;
        }

        /**
         * Sets the value of the urlStyle property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUrlStyle(String value) {
            this.urlStyle = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="authorizedOrganization" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;extension base="{}Id">
         *                 &lt;sequence>
         *                   &lt;element name="accessMethod" maxOccurs="unbounded" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="networkAccessMethod" type="{}CD" minOccurs="0"/>
         *                             &lt;element name="authenticationMethod">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;choice>
         *                                       &lt;element name="ip">
         *                                         &lt;complexType>
         *                                           &lt;complexContent>
         *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                               &lt;sequence>
         *                                                 &lt;element name="ipRange" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded"/>
         *                                               &lt;/sequence>
         *                                             &lt;/restriction>
         *                                           &lt;/complexContent>
         *                                         &lt;/complexType>
         *                                       &lt;/element>
         *                                       &lt;element name="usrPwd">
         *                                         &lt;complexType>
         *                                           &lt;complexContent>
         *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                               &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *                                               &lt;attribute name="certificateText" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *                                             &lt;/restriction>
         *                                           &lt;/complexContent>
         *                                         &lt;/complexType>
         *                                       &lt;/element>
         *                                     &lt;/choice>
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/extension>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "authorizedOrganization"
        })
        public static class AuthorizedOrganizations {

            @XmlElement(required = true)
            protected List<KnowledgeResourceProfile.ProfileDefinition.AuthorizedOrganizations.AuthorizedOrganization> authorizedOrganization;

            /**
             * Gets the value of the authorizedOrganization property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the authorizedOrganization property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getAuthorizedOrganization().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link KnowledgeResourceProfile.ProfileDefinition.AuthorizedOrganizations.AuthorizedOrganization }
             * 
             * 
             */
            public List<KnowledgeResourceProfile.ProfileDefinition.AuthorizedOrganizations.AuthorizedOrganization> getAuthorizedOrganization() {
                if (authorizedOrganization == null) {
                    authorizedOrganization = new ArrayList<KnowledgeResourceProfile.ProfileDefinition.AuthorizedOrganizations.AuthorizedOrganization>();
                }
                return this.authorizedOrganization;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;extension base="{}Id">
             *       &lt;sequence>
             *         &lt;element name="accessMethod" maxOccurs="unbounded" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="networkAccessMethod" type="{}CD" minOccurs="0"/>
             *                   &lt;element name="authenticationMethod">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;choice>
             *                             &lt;element name="ip">
             *                               &lt;complexType>
             *                                 &lt;complexContent>
             *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                                     &lt;sequence>
             *                                       &lt;element name="ipRange" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded"/>
             *                                     &lt;/sequence>
             *                                   &lt;/restriction>
             *                                 &lt;/complexContent>
             *                               &lt;/complexType>
             *                             &lt;/element>
             *                             &lt;element name="usrPwd">
             *                               &lt;complexType>
             *                                 &lt;complexContent>
             *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                                     &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
             *                                     &lt;attribute name="certificateText" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
             *                                   &lt;/restriction>
             *                                 &lt;/complexContent>
             *                               &lt;/complexType>
             *                             &lt;/element>
             *                           &lt;/choice>
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/extension>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "accessMethod"
            })
            public static class AuthorizedOrganization
                extends Id
            {

                protected List<KnowledgeResourceProfile.ProfileDefinition.AuthorizedOrganizations.AuthorizedOrganization.AccessMethod> accessMethod;

                /**
                 * Gets the value of the accessMethod property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the accessMethod property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getAccessMethod().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link KnowledgeResourceProfile.ProfileDefinition.AuthorizedOrganizations.AuthorizedOrganization.AccessMethod }
                 * 
                 * 
                 */
                public List<KnowledgeResourceProfile.ProfileDefinition.AuthorizedOrganizations.AuthorizedOrganization.AccessMethod> getAccessMethod() {
                    if (accessMethod == null) {
                        accessMethod = new ArrayList<KnowledgeResourceProfile.ProfileDefinition.AuthorizedOrganizations.AuthorizedOrganization.AccessMethod>();
                    }
                    return this.accessMethod;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="networkAccessMethod" type="{}CD" minOccurs="0"/>
                 *         &lt;element name="authenticationMethod">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;choice>
                 *                   &lt;element name="ip">
                 *                     &lt;complexType>
                 *                       &lt;complexContent>
                 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                           &lt;sequence>
                 *                             &lt;element name="ipRange" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded"/>
                 *                           &lt;/sequence>
                 *                         &lt;/restriction>
                 *                       &lt;/complexContent>
                 *                     &lt;/complexType>
                 *                   &lt;/element>
                 *                   &lt;element name="usrPwd">
                 *                     &lt;complexType>
                 *                       &lt;complexContent>
                 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                           &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
                 *                           &lt;attribute name="certificateText" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
                 *                         &lt;/restriction>
                 *                       &lt;/complexContent>
                 *                     &lt;/complexType>
                 *                   &lt;/element>
                 *                 &lt;/choice>
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "networkAccessMethod",
                    "authenticationMethod"
                })
                public static class AccessMethod {

                    protected CD networkAccessMethod;
                    @XmlElement(required = true)
                    protected KnowledgeResourceProfile.ProfileDefinition.AuthorizedOrganizations.AuthorizedOrganization.AccessMethod.AuthenticationMethod authenticationMethod;

                    /**
                     * Gets the value of the networkAccessMethod property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link CD }
                     *     
                     */
                    public CD getNetworkAccessMethod() {
                        return networkAccessMethod;
                    }

                    /**
                     * Sets the value of the networkAccessMethod property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link CD }
                     *     
                     */
                    public void setNetworkAccessMethod(CD value) {
                        this.networkAccessMethod = value;
                    }

                    /**
                     * Gets the value of the authenticationMethod property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link KnowledgeResourceProfile.ProfileDefinition.AuthorizedOrganizations.AuthorizedOrganization.AccessMethod.AuthenticationMethod }
                     *     
                     */
                    public KnowledgeResourceProfile.ProfileDefinition.AuthorizedOrganizations.AuthorizedOrganization.AccessMethod.AuthenticationMethod getAuthenticationMethod() {
                        return authenticationMethod;
                    }

                    /**
                     * Sets the value of the authenticationMethod property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link KnowledgeResourceProfile.ProfileDefinition.AuthorizedOrganizations.AuthorizedOrganization.AccessMethod.AuthenticationMethod }
                     *     
                     */
                    public void setAuthenticationMethod(KnowledgeResourceProfile.ProfileDefinition.AuthorizedOrganizations.AuthorizedOrganization.AccessMethod.AuthenticationMethod value) {
                        this.authenticationMethod = value;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;choice>
                     *         &lt;element name="ip">
                     *           &lt;complexType>
                     *             &lt;complexContent>
                     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *                 &lt;sequence>
                     *                   &lt;element name="ipRange" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded"/>
                     *                 &lt;/sequence>
                     *               &lt;/restriction>
                     *             &lt;/complexContent>
                     *           &lt;/complexType>
                     *         &lt;/element>
                     *         &lt;element name="usrPwd">
                     *           &lt;complexType>
                     *             &lt;complexContent>
                     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
                     *                 &lt;attribute name="certificateText" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
                     *               &lt;/restriction>
                     *             &lt;/complexContent>
                     *           &lt;/complexType>
                     *         &lt;/element>
                     *       &lt;/choice>
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "ip",
                        "usrPwd"
                    })
                    public static class AuthenticationMethod {

                        protected KnowledgeResourceProfile.ProfileDefinition.AuthorizedOrganizations.AuthorizedOrganization.AccessMethod.AuthenticationMethod.Ip ip;
                        protected KnowledgeResourceProfile.ProfileDefinition.AuthorizedOrganizations.AuthorizedOrganization.AccessMethod.AuthenticationMethod.UsrPwd usrPwd;

                        /**
                         * Gets the value of the ip property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link KnowledgeResourceProfile.ProfileDefinition.AuthorizedOrganizations.AuthorizedOrganization.AccessMethod.AuthenticationMethod.Ip }
                         *     
                         */
                        public KnowledgeResourceProfile.ProfileDefinition.AuthorizedOrganizations.AuthorizedOrganization.AccessMethod.AuthenticationMethod.Ip getIp() {
                            return ip;
                        }

                        /**
                         * Sets the value of the ip property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link KnowledgeResourceProfile.ProfileDefinition.AuthorizedOrganizations.AuthorizedOrganization.AccessMethod.AuthenticationMethod.Ip }
                         *     
                         */
                        public void setIp(KnowledgeResourceProfile.ProfileDefinition.AuthorizedOrganizations.AuthorizedOrganization.AccessMethod.AuthenticationMethod.Ip value) {
                            this.ip = value;
                        }

                        /**
                         * Gets the value of the usrPwd property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link KnowledgeResourceProfile.ProfileDefinition.AuthorizedOrganizations.AuthorizedOrganization.AccessMethod.AuthenticationMethod.UsrPwd }
                         *     
                         */
                        public KnowledgeResourceProfile.ProfileDefinition.AuthorizedOrganizations.AuthorizedOrganization.AccessMethod.AuthenticationMethod.UsrPwd getUsrPwd() {
                            return usrPwd;
                        }

                        /**
                         * Sets the value of the usrPwd property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link KnowledgeResourceProfile.ProfileDefinition.AuthorizedOrganizations.AuthorizedOrganization.AccessMethod.AuthenticationMethod.UsrPwd }
                         *     
                         */
                        public void setUsrPwd(KnowledgeResourceProfile.ProfileDefinition.AuthorizedOrganizations.AuthorizedOrganization.AccessMethod.AuthenticationMethod.UsrPwd value) {
                            this.usrPwd = value;
                        }


                        /**
                         * <p>Java class for anonymous complex type.
                         * 
                         * <p>The following schema fragment specifies the expected content contained within this class.
                         * 
                         * <pre>
                         * &lt;complexType>
                         *   &lt;complexContent>
                         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                         *       &lt;sequence>
                         *         &lt;element name="ipRange" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded"/>
                         *       &lt;/sequence>
                         *     &lt;/restriction>
                         *   &lt;/complexContent>
                         * &lt;/complexType>
                         * </pre>
                         * 
                         * 
                         */
                        @XmlAccessorType(XmlAccessType.FIELD)
                        @XmlType(name = "", propOrder = {
                            "ipRange"
                        })
                        public static class Ip {

                            @XmlElement(required = true)
                            protected List<Object> ipRange;

                            /**
                             * Gets the value of the ipRange property.
                             * 
                             * <p>
                             * This accessor method returns a reference to the live list,
                             * not a snapshot. Therefore any modification you make to the
                             * returned list will be present inside the JAXB object.
                             * This is why there is not a <CODE>set</CODE> method for the ipRange property.
                             * 
                             * <p>
                             * For example, to add a new item, do as follows:
                             * <pre>
                             *    getIpRange().add(newItem);
                             * </pre>
                             * 
                             * 
                             * <p>
                             * Objects of the following type(s) are allowed in the list
                             * {@link Object }
                             * 
                             * 
                             */
                            public List<Object> getIpRange() {
                                if (ipRange == null) {
                                    ipRange = new ArrayList<Object>();
                                }
                                return this.ipRange;
                            }

                        }


                        /**
                         * <p>Java class for anonymous complex type.
                         * 
                         * <p>The following schema fragment specifies the expected content contained within this class.
                         * 
                         * <pre>
                         * &lt;complexType>
                         *   &lt;complexContent>
                         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                         *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
                         *       &lt;attribute name="certificateText" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
                         *     &lt;/restriction>
                         *   &lt;/complexContent>
                         * &lt;/complexType>
                         * </pre>
                         * 
                         * 
                         */
                        @XmlAccessorType(XmlAccessType.FIELD)
                        @XmlType(name = "")
                        public static class UsrPwd {

                            @XmlAttribute(required = true)
                            @XmlSchemaType(name = "anySimpleType")
                            protected String name;
                            @XmlAttribute(required = true)
                            @XmlSchemaType(name = "anySimpleType")
                            protected String certificateText;

                            /**
                             * Gets the value of the name property.
                             * 
                             * @return
                             *     possible object is
                             *     {@link String }
                             *     
                             */
                            public String getName() {
                                return name;
                            }

                            /**
                             * Sets the value of the name property.
                             * 
                             * @param value
                             *     allowed object is
                             *     {@link String }
                             *     
                             */
                            public void setName(String value) {
                                this.name = value;
                            }

                            /**
                             * Gets the value of the certificateText property.
                             * 
                             * @return
                             *     possible object is
                             *     {@link String }
                             *     
                             */
                            public String getCertificateText() {
                                return certificateText;
                            }

                            /**
                             * Sets the value of the certificateText property.
                             * 
                             * @param value
                             *     allowed object is
                             *     {@link String }
                             *     
                             */
                            public void setCertificateText(String value) {
                                this.certificateText = value;
                            }

                        }

                    }

                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="context" type="{}Context" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "context"
        })
        public static class Contexts {

            @XmlElement(required = true)
            protected List<Context> context;

            /**
             * Gets the value of the context property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the context property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getContext().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Context }
             * 
             * 
             */
            public List<Context> getContext() {
                if (context == null) {
                    context = new ArrayList<Context>();
                }
                return this.context;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="supportedTerminology" type="{}Id" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "supportedTerminology"
        })
        public static class SupportedTerminologies {

            @XmlElement(required = true)
            protected List<Id> supportedTerminology;

            /**
             * Gets the value of the supportedTerminology property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the supportedTerminology property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getSupportedTerminology().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Id }
             * 
             * 
             */
            public List<Id> getSupportedTerminology() {
                if (supportedTerminology == null) {
                    supportedTerminology = new ArrayList<Id>();
                }
                return this.supportedTerminology;
            }

        }

    }

}
