//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.02 at 12:23:52 PM MST 
//


package org.openinfobutton.schemas.kb;

import java.util.HashMap;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.kscs.util.jaxb.Buildable;
import com.kscs.util.jaxb.PropertyTree;
import com.kscs.util.jaxb.PropertyTreeUse;


/**
 * <p>Java class for ContactType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ContactType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}name"/&gt;
 *         &lt;element ref="{}contactInformation"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContactType", propOrder = {
    "name",
    "contactInformation"
})
public class ContactType {

    @XmlElement(required = true)
    protected Name name;
    @XmlElement(required = true)
    protected ContactInformation contactInformation;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link Name }
     *     
     */
    public Name getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link Name }
     *     
     */
    public void setName(Name value) {
        this.name = value;
    }

    /**
     * Gets the value of the contactInformation property.
     * 
     * @return
     *     possible object is
     *     {@link ContactInformation }
     *     
     */
    public ContactInformation getContactInformation() {
        return contactInformation;
    }

    /**
     * Sets the value of the contactInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactInformation }
     *     
     */
    public void setContactInformation(ContactInformation value) {
        this.contactInformation = value;
    }

    /**
     * Copies all state of this object to a builder. This method is used by the {@link #copyOf} method and should not be called directly by client code.
     * 
     * @param _other
     *     A builder instance to which the state of this object will be copied.
     */
    public<_B >void copyTo(final ContactType.Builder<_B> _other) {
        _other.name = ((this.name == null)?null:this.name.newCopyBuilder(_other));
        _other.contactInformation = ((this.contactInformation == null)?null:this.contactInformation.newCopyBuilder(_other));
    }

    public<_B >ContactType.Builder<_B> newCopyBuilder(final _B _parentBuilder) {
        return new ContactType.Builder<_B>(_parentBuilder, this, true);
    }

    public ContactType.Builder<Void> newCopyBuilder() {
        return newCopyBuilder(null);
    }

    public static ContactType.Builder<Void> builder() {
        return new ContactType.Builder<Void>(null, null, false);
    }

    public static<_B >ContactType.Builder<_B> copyOf(final ContactType _other) {
        final ContactType.Builder<_B> _newBuilder = new ContactType.Builder<_B>(null, null, false);
        _other.copyTo(_newBuilder);
        return _newBuilder;
    }

    /**
     * Copies all state of this object to a builder. This method is used by the {@link #copyOf} method and should not be called directly by client code.
     * 
     * @param _other
     *     A builder instance to which the state of this object will be copied.
     */
    public<_B >void copyTo(final ContactType.Builder<_B> _other, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        final PropertyTree namePropertyTree = ((_propertyTree == null)?null:_propertyTree.get("name"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(namePropertyTree!= null):((namePropertyTree == null)||(!namePropertyTree.isLeaf())))) {
            _other.name = ((this.name == null)?null:this.name.newCopyBuilder(_other, namePropertyTree, _propertyTreeUse));
        }
        final PropertyTree contactInformationPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("contactInformation"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(contactInformationPropertyTree!= null):((contactInformationPropertyTree == null)||(!contactInformationPropertyTree.isLeaf())))) {
            _other.contactInformation = ((this.contactInformation == null)?null:this.contactInformation.newCopyBuilder(_other, contactInformationPropertyTree, _propertyTreeUse));
        }
    }

    public<_B >ContactType.Builder<_B> newCopyBuilder(final _B _parentBuilder, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        return new ContactType.Builder<_B>(_parentBuilder, this, true, _propertyTree, _propertyTreeUse);
    }

    public ContactType.Builder<Void> newCopyBuilder(final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        return newCopyBuilder(null, _propertyTree, _propertyTreeUse);
    }

    public static<_B >ContactType.Builder<_B> copyOf(final ContactType _other, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        final ContactType.Builder<_B> _newBuilder = new ContactType.Builder<_B>(null, null, false);
        _other.copyTo(_newBuilder, _propertyTree, _propertyTreeUse);
        return _newBuilder;
    }

    public static ContactType.Builder<Void> copyExcept(final ContactType _other, final PropertyTree _propertyTree) {
        return copyOf(_other, _propertyTree, PropertyTreeUse.EXCLUDE);
    }

    public static ContactType.Builder<Void> copyOnly(final ContactType _other, final PropertyTree _propertyTree) {
        return copyOf(_other, _propertyTree, PropertyTreeUse.INCLUDE);
    }

    public static class Builder<_B >implements Buildable
    {

        protected final _B _parentBuilder;
        protected final ContactType _storedValue;
        private Name.Builder<ContactType.Builder<_B>> name;
        private ContactInformation.Builder<ContactType.Builder<_B>> contactInformation;

        public Builder(final _B _parentBuilder, final ContactType _other, final boolean _copy) {
            this._parentBuilder = _parentBuilder;
            if (_other!= null) {
                if (_copy) {
                    _storedValue = null;
                    this.name = ((_other.name == null)?null:_other.name.newCopyBuilder(this));
                    this.contactInformation = ((_other.contactInformation == null)?null:_other.contactInformation.newCopyBuilder(this));
                } else {
                    _storedValue = _other;
                }
            } else {
                _storedValue = null;
            }
        }

        public Builder(final _B _parentBuilder, final ContactType _other, final boolean _copy, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
            this._parentBuilder = _parentBuilder;
            if (_other!= null) {
                if (_copy) {
                    _storedValue = null;
                    final PropertyTree namePropertyTree = ((_propertyTree == null)?null:_propertyTree.get("name"));
                    if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(namePropertyTree!= null):((namePropertyTree == null)||(!namePropertyTree.isLeaf())))) {
                        this.name = ((_other.name == null)?null:_other.name.newCopyBuilder(this, namePropertyTree, _propertyTreeUse));
                    }
                    final PropertyTree contactInformationPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("contactInformation"));
                    if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(contactInformationPropertyTree!= null):((contactInformationPropertyTree == null)||(!contactInformationPropertyTree.isLeaf())))) {
                        this.contactInformation = ((_other.contactInformation == null)?null:_other.contactInformation.newCopyBuilder(this, contactInformationPropertyTree, _propertyTreeUse));
                    }
                } else {
                    _storedValue = _other;
                }
            } else {
                _storedValue = null;
            }
        }

        public _B end() {
            return this._parentBuilder;
        }

        protected<_P extends ContactType >_P init(final _P _product) {
            _product.name = ((this.name == null)?null:this.name.build());
            _product.contactInformation = ((this.contactInformation == null)?null:this.contactInformation.build());
            return _product;
        }

        /**
         * Sets the new value of "name" (any previous value will be replaced)
         * 
         * @param name
         *     New value of the "name" property.
         */
        public ContactType.Builder<_B> withName(final Name name) {
            this.name = ((name == null)?null:new Name.Builder<ContactType.Builder<_B>>(this, name, false));
            return this;
        }

        /**
         * Returns a new builder to build the value of the "name" property (replacing previous value).
         * Use {@link org.openinfobutton.schemas.kb.Name.Builder#end()} to return to the current builder.
         * 
         * @return
         *     A new builder to build the value of the "name" property.
         *     Use {@link org.openinfobutton.schemas.kb.Name.Builder#end()} to return to the current builder.
         */
        public Name.Builder<? extends ContactType.Builder<_B>> withName() {
            return this.name = new Name.Builder<ContactType.Builder<_B>>(this, null, false);
        }

        /**
         * Sets the new value of "contactInformation" (any previous value will be replaced)
         * 
         * @param contactInformation
         *     New value of the "contactInformation" property.
         */
        public ContactType.Builder<_B> withContactInformation(final ContactInformation contactInformation) {
            this.contactInformation = ((contactInformation == null)?null:new ContactInformation.Builder<ContactType.Builder<_B>>(this, contactInformation, false));
            return this;
        }

        /**
         * Returns a new builder to build the value of the "contactInformation" property (replacing previous value).
         * Use {@link org.openinfobutton.schemas.kb.ContactInformation.Builder#end()} to return to the current builder.
         * 
         * @return
         *     A new builder to build the value of the "contactInformation" property.
         *     Use {@link org.openinfobutton.schemas.kb.ContactInformation.Builder#end()} to return to the current builder.
         */
        public ContactInformation.Builder<? extends ContactType.Builder<_B>> withContactInformation() {
            return this.contactInformation = new ContactInformation.Builder<ContactType.Builder<_B>>(this, null, false);
        }

        @Override
        public ContactType build() {
            if (_storedValue == null) {
                return this.init(new ContactType());
            } else {
                return ((ContactType) _storedValue);
            }
        }

    }

    public static class Select
        extends ContactType.Selector<ContactType.Select, Void>
    {


        Select() {
            super(null, null, null);
        }

        public static ContactType.Select _root() {
            return new ContactType.Select();
        }

    }

    public static class Selector<TRoot extends com.kscs.util.jaxb.Selector<TRoot, ?> , TParent >
        extends com.kscs.util.jaxb.Selector<TRoot, TParent>
    {

        private Name.Selector<TRoot, ContactType.Selector<TRoot, TParent>> name = null;
        private ContactInformation.Selector<TRoot, ContactType.Selector<TRoot, TParent>> contactInformation = null;

        public Selector(final TRoot root, final TParent parent, final String propertyName) {
            super(root, parent, propertyName);
        }

        @Override
        public Map<String, PropertyTree> buildChildren() {
            final Map<String, PropertyTree> products = new HashMap<String, PropertyTree>();
            products.putAll(super.buildChildren());
            if (this.name!= null) {
                products.put("name", this.name.init());
            }
            if (this.contactInformation!= null) {
                products.put("contactInformation", this.contactInformation.init());
            }
            return products;
        }

        public Name.Selector<TRoot, ContactType.Selector<TRoot, TParent>> name() {
            return ((this.name == null)?this.name = new Name.Selector<TRoot, ContactType.Selector<TRoot, TParent>>(this._root, this, "name"):this.name);
        }

        public ContactInformation.Selector<TRoot, ContactType.Selector<TRoot, TParent>> contactInformation() {
            return ((this.contactInformation == null)?this.contactInformation = new ContactInformation.Selector<TRoot, ContactType.Selector<TRoot, TParent>>(this._root, this, "contactInformation"):this.contactInformation);
        }

    }

}
