//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.07 at 12:37:02 PM MST 
//


package org.openinfobutton.schemas.kb;

import java.util.HashMap;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import com.kscs.util.jaxb.Buildable;
import com.kscs.util.jaxb.PropertyTree;
import com.kscs.util.jaxb.PropertyTreeUse;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute ref="{}url use="required""/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "knowledgeRequestServiceLocation")
public class KnowledgeRequestServiceLocation {

    @XmlAttribute(name = "url", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String url;

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrl() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrl(String value) {
        this.url = value;
    }

    /**
     * Copies all state of this object to a builder. This method is used by the {@link #copyOf} method and should not be called directly by client code.
     * 
     * @param _other
     *     A builder instance to which the state of this object will be copied.
     */
    public<_B >void copyTo(final KnowledgeRequestServiceLocation.Builder<_B> _other) {
        _other.url = this.url;
    }

    public<_B >KnowledgeRequestServiceLocation.Builder<_B> newCopyBuilder(final _B _parentBuilder) {
        return new KnowledgeRequestServiceLocation.Builder<_B>(_parentBuilder, this, true);
    }

    public KnowledgeRequestServiceLocation.Builder<Void> newCopyBuilder() {
        return newCopyBuilder(null);
    }

    public static KnowledgeRequestServiceLocation.Builder<Void> builder() {
        return new KnowledgeRequestServiceLocation.Builder<Void>(null, null, false);
    }

    public static<_B >KnowledgeRequestServiceLocation.Builder<_B> copyOf(final KnowledgeRequestServiceLocation _other) {
        final KnowledgeRequestServiceLocation.Builder<_B> _newBuilder = new KnowledgeRequestServiceLocation.Builder<_B>(null, null, false);
        _other.copyTo(_newBuilder);
        return _newBuilder;
    }

    /**
     * Copies all state of this object to a builder. This method is used by the {@link #copyOf} method and should not be called directly by client code.
     * 
     * @param _other
     *     A builder instance to which the state of this object will be copied.
     */
    public<_B >void copyTo(final KnowledgeRequestServiceLocation.Builder<_B> _other, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        final PropertyTree urlPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("url"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(urlPropertyTree!= null):((urlPropertyTree == null)||(!urlPropertyTree.isLeaf())))) {
            _other.url = this.url;
        }
    }

    public<_B >KnowledgeRequestServiceLocation.Builder<_B> newCopyBuilder(final _B _parentBuilder, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        return new KnowledgeRequestServiceLocation.Builder<_B>(_parentBuilder, this, true, _propertyTree, _propertyTreeUse);
    }

    public KnowledgeRequestServiceLocation.Builder<Void> newCopyBuilder(final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        return newCopyBuilder(null, _propertyTree, _propertyTreeUse);
    }

    public static<_B >KnowledgeRequestServiceLocation.Builder<_B> copyOf(final KnowledgeRequestServiceLocation _other, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        final KnowledgeRequestServiceLocation.Builder<_B> _newBuilder = new KnowledgeRequestServiceLocation.Builder<_B>(null, null, false);
        _other.copyTo(_newBuilder, _propertyTree, _propertyTreeUse);
        return _newBuilder;
    }

    public static KnowledgeRequestServiceLocation.Builder<Void> copyExcept(final KnowledgeRequestServiceLocation _other, final PropertyTree _propertyTree) {
        return copyOf(_other, _propertyTree, PropertyTreeUse.EXCLUDE);
    }

    public static KnowledgeRequestServiceLocation.Builder<Void> copyOnly(final KnowledgeRequestServiceLocation _other, final PropertyTree _propertyTree) {
        return copyOf(_other, _propertyTree, PropertyTreeUse.INCLUDE);
    }

    public static class Builder<_B >implements Buildable
    {

        protected final _B _parentBuilder;
        protected final KnowledgeRequestServiceLocation _storedValue;
        private String url;

        public Builder(final _B _parentBuilder, final KnowledgeRequestServiceLocation _other, final boolean _copy) {
            this._parentBuilder = _parentBuilder;
            if (_other!= null) {
                if (_copy) {
                    _storedValue = null;
                    this.url = _other.url;
                } else {
                    _storedValue = _other;
                }
            } else {
                _storedValue = null;
            }
        }

        public Builder(final _B _parentBuilder, final KnowledgeRequestServiceLocation _other, final boolean _copy, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
            this._parentBuilder = _parentBuilder;
            if (_other!= null) {
                if (_copy) {
                    _storedValue = null;
                    final PropertyTree urlPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("url"));
                    if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(urlPropertyTree!= null):((urlPropertyTree == null)||(!urlPropertyTree.isLeaf())))) {
                        this.url = _other.url;
                    }
                } else {
                    _storedValue = _other;
                }
            } else {
                _storedValue = null;
            }
        }

        public _B end() {
            return this._parentBuilder;
        }

        protected<_P extends KnowledgeRequestServiceLocation >_P init(final _P _product) {
            _product.url = this.url;
            return _product;
        }

        /**
         * Sets the new value of "url" (any previous value will be replaced)
         * 
         * @param url
         *     New value of the "url" property.
         */
        public KnowledgeRequestServiceLocation.Builder<_B> withUrl(final String url) {
            this.url = url;
            return this;
        }

        @Override
        public KnowledgeRequestServiceLocation build() {
            if (_storedValue == null) {
                return this.init(new KnowledgeRequestServiceLocation());
            } else {
                return ((KnowledgeRequestServiceLocation) _storedValue);
            }
        }

    }

    public static class Select
        extends KnowledgeRequestServiceLocation.Selector<KnowledgeRequestServiceLocation.Select, Void>
    {


        Select() {
            super(null, null, null);
        }

        public static KnowledgeRequestServiceLocation.Select _root() {
            return new KnowledgeRequestServiceLocation.Select();
        }

    }

    public static class Selector<TRoot extends com.kscs.util.jaxb.Selector<TRoot, ?> , TParent >
        extends com.kscs.util.jaxb.Selector<TRoot, TParent>
    {

        private com.kscs.util.jaxb.Selector<TRoot, KnowledgeRequestServiceLocation.Selector<TRoot, TParent>> url = null;

        public Selector(final TRoot root, final TParent parent, final String propertyName) {
            super(root, parent, propertyName);
        }

        @Override
        public Map<String, PropertyTree> buildChildren() {
            final Map<String, PropertyTree> products = new HashMap<String, PropertyTree>();
            products.putAll(super.buildChildren());
            if (this.url!= null) {
                products.put("url", this.url.init());
            }
            return products;
        }

        public com.kscs.util.jaxb.Selector<TRoot, KnowledgeRequestServiceLocation.Selector<TRoot, TParent>> url() {
            return ((this.url == null)?this.url = new com.kscs.util.jaxb.Selector<TRoot, KnowledgeRequestServiceLocation.Selector<TRoot, TParent>>(this._root, this, "url"):this.url);
        }

    }

}
