//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.01 at 10:57:27 AM MST 
//


package org.openinfobutton.schemas.kb;

import java.math.BigInteger;
import java.util.HashMap;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import com.kscs.util.jaxb.Buildable;
import com.kscs.util.jaxb.PropertyTree;
import com.kscs.util.jaxb.PropertyTreeUse;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="header"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="title" type="{}ST"/&gt;
 *                   &lt;element name="profileDescription" type="{}ST"/&gt;
 *                   &lt;element name="versionControl"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;attribute name="publicationDate" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="profileDefinition" type="{}profileDefinition"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "header",
    "profileDefinition"
})
@XmlRootElement(name = "knowledgeResourceProfile")
public class KnowledgeResourceProfile {

    @XmlElement(required = true)
    protected KnowledgeResourceProfile.Header header;
    @XmlElement(required = true)
    protected ProfileDefinition profileDefinition;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link KnowledgeResourceProfile.Header }
     *     
     */
    public KnowledgeResourceProfile.Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link KnowledgeResourceProfile.Header }
     *     
     */
    public void setHeader(KnowledgeResourceProfile.Header value) {
        this.header = value;
    }

    /**
     * Gets the value of the profileDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link ProfileDefinition }
     *     
     */
    public ProfileDefinition getProfileDefinition() {
        return profileDefinition;
    }

    /**
     * Sets the value of the profileDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProfileDefinition }
     *     
     */
    public void setProfileDefinition(ProfileDefinition value) {
        this.profileDefinition = value;
    }

    /**
     * Copies all state of this object to a builder. This method is used by the {@link #copyOf} method and should not be called directly by client code.
     * 
     * @param _other
     *     A builder instance to which the state of this object will be copied.
     */
    public<_B >void copyTo(final KnowledgeResourceProfile.Builder<_B> _other) {
        _other.header = ((this.header == null)?null:this.header.newCopyBuilder(_other));
        _other.profileDefinition = ((this.profileDefinition == null)?null:this.profileDefinition.newCopyBuilder(_other));
    }

    public<_B >KnowledgeResourceProfile.Builder<_B> newCopyBuilder(final _B _parentBuilder) {
        return new KnowledgeResourceProfile.Builder<_B>(_parentBuilder, this, true);
    }

    public KnowledgeResourceProfile.Builder<Void> newCopyBuilder() {
        return newCopyBuilder(null);
    }

    public static KnowledgeResourceProfile.Builder<Void> builder() {
        return new KnowledgeResourceProfile.Builder<Void>(null, null, false);
    }

    public static<_B >KnowledgeResourceProfile.Builder<_B> copyOf(final KnowledgeResourceProfile _other) {
        final KnowledgeResourceProfile.Builder<_B> _newBuilder = new KnowledgeResourceProfile.Builder<_B>(null, null, false);
        _other.copyTo(_newBuilder);
        return _newBuilder;
    }

    /**
     * Copies all state of this object to a builder. This method is used by the {@link #copyOf} method and should not be called directly by client code.
     * 
     * @param _other
     *     A builder instance to which the state of this object will be copied.
     */
    public<_B >void copyTo(final KnowledgeResourceProfile.Builder<_B> _other, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        final PropertyTree headerPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("header"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(headerPropertyTree!= null):((headerPropertyTree == null)||(!headerPropertyTree.isLeaf())))) {
            _other.header = ((this.header == null)?null:this.header.newCopyBuilder(_other, headerPropertyTree, _propertyTreeUse));
        }
        final PropertyTree profileDefinitionPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("profileDefinition"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(profileDefinitionPropertyTree!= null):((profileDefinitionPropertyTree == null)||(!profileDefinitionPropertyTree.isLeaf())))) {
            _other.profileDefinition = ((this.profileDefinition == null)?null:this.profileDefinition.newCopyBuilder(_other, profileDefinitionPropertyTree, _propertyTreeUse));
        }
    }

    public<_B >KnowledgeResourceProfile.Builder<_B> newCopyBuilder(final _B _parentBuilder, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        return new KnowledgeResourceProfile.Builder<_B>(_parentBuilder, this, true, _propertyTree, _propertyTreeUse);
    }

    public KnowledgeResourceProfile.Builder<Void> newCopyBuilder(final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        return newCopyBuilder(null, _propertyTree, _propertyTreeUse);
    }

    public static<_B >KnowledgeResourceProfile.Builder<_B> copyOf(final KnowledgeResourceProfile _other, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        final KnowledgeResourceProfile.Builder<_B> _newBuilder = new KnowledgeResourceProfile.Builder<_B>(null, null, false);
        _other.copyTo(_newBuilder, _propertyTree, _propertyTreeUse);
        return _newBuilder;
    }

    public static KnowledgeResourceProfile.Builder<Void> copyExcept(final KnowledgeResourceProfile _other, final PropertyTree _propertyTree) {
        return copyOf(_other, _propertyTree, PropertyTreeUse.EXCLUDE);
    }

    public static KnowledgeResourceProfile.Builder<Void> copyOnly(final KnowledgeResourceProfile _other, final PropertyTree _propertyTree) {
        return copyOf(_other, _propertyTree, PropertyTreeUse.INCLUDE);
    }

    public static class Builder<_B >implements Buildable
    {

        protected final _B _parentBuilder;
        protected final KnowledgeResourceProfile _storedValue;
        private KnowledgeResourceProfile.Header.Builder<KnowledgeResourceProfile.Builder<_B>> header;
        private ProfileDefinition.Builder<KnowledgeResourceProfile.Builder<_B>> profileDefinition;

        public Builder(final _B _parentBuilder, final KnowledgeResourceProfile _other, final boolean _copy) {
            this._parentBuilder = _parentBuilder;
            if (_other!= null) {
                if (_copy) {
                    _storedValue = null;
                    this.header = ((_other.header == null)?null:_other.header.newCopyBuilder(this));
                    this.profileDefinition = ((_other.profileDefinition == null)?null:_other.profileDefinition.newCopyBuilder(this));
                } else {
                    _storedValue = _other;
                }
            } else {
                _storedValue = null;
            }
        }

        public Builder(final _B _parentBuilder, final KnowledgeResourceProfile _other, final boolean _copy, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
            this._parentBuilder = _parentBuilder;
            if (_other!= null) {
                if (_copy) {
                    _storedValue = null;
                    final PropertyTree headerPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("header"));
                    if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(headerPropertyTree!= null):((headerPropertyTree == null)||(!headerPropertyTree.isLeaf())))) {
                        this.header = ((_other.header == null)?null:_other.header.newCopyBuilder(this, headerPropertyTree, _propertyTreeUse));
                    }
                    final PropertyTree profileDefinitionPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("profileDefinition"));
                    if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(profileDefinitionPropertyTree!= null):((profileDefinitionPropertyTree == null)||(!profileDefinitionPropertyTree.isLeaf())))) {
                        this.profileDefinition = ((_other.profileDefinition == null)?null:_other.profileDefinition.newCopyBuilder(this, profileDefinitionPropertyTree, _propertyTreeUse));
                    }
                } else {
                    _storedValue = _other;
                }
            } else {
                _storedValue = null;
            }
        }

        public _B end() {
            return this._parentBuilder;
        }

        protected<_P extends KnowledgeResourceProfile >_P init(final _P _product) {
            _product.header = ((this.header == null)?null:this.header.build());
            _product.profileDefinition = ((this.profileDefinition == null)?null:this.profileDefinition.build());
            return _product;
        }

        /**
         * Sets the new value of "header" (any previous value will be replaced)
         * 
         * @param header
         *     New value of the "header" property.
         */
        public KnowledgeResourceProfile.Builder<_B> withHeader(final KnowledgeResourceProfile.Header header) {
            this.header = ((header == null)?null:new KnowledgeResourceProfile.Header.Builder<KnowledgeResourceProfile.Builder<_B>>(this, header, false));
            return this;
        }

        /**
         * Returns a new builder to build the value of the "header" property (replacing previous value).
         * Use {@link org.openinfobutton.schemas.kb.KnowledgeResourceProfile.Header.Builder#end()} to return to the current builder.
         * 
         * @return
         *     A new builder to build the value of the "header" property.
         *     Use {@link org.openinfobutton.schemas.kb.KnowledgeResourceProfile.Header.Builder#end()} to return to the current builder.
         */
        public KnowledgeResourceProfile.Header.Builder<? extends KnowledgeResourceProfile.Builder<_B>> withHeader() {
            return this.header = new KnowledgeResourceProfile.Header.Builder<KnowledgeResourceProfile.Builder<_B>>(this, null, false);
        }

        /**
         * Sets the new value of "profileDefinition" (any previous value will be replaced)
         * 
         * @param profileDefinition
         *     New value of the "profileDefinition" property.
         */
        public KnowledgeResourceProfile.Builder<_B> withProfileDefinition(final ProfileDefinition profileDefinition) {
            this.profileDefinition = ((profileDefinition == null)?null:new ProfileDefinition.Builder<KnowledgeResourceProfile.Builder<_B>>(this, profileDefinition, false));
            return this;
        }

        /**
         * Returns a new builder to build the value of the "profileDefinition" property (replacing previous value).
         * Use {@link org.openinfobutton.schemas.kb.ProfileDefinition.Builder#end()} to return to the current builder.
         * 
         * @return
         *     A new builder to build the value of the "profileDefinition" property.
         *     Use {@link org.openinfobutton.schemas.kb.ProfileDefinition.Builder#end()} to return to the current builder.
         */
        public ProfileDefinition.Builder<? extends KnowledgeResourceProfile.Builder<_B>> withProfileDefinition() {
            return this.profileDefinition = new ProfileDefinition.Builder<KnowledgeResourceProfile.Builder<_B>>(this, null, false);
        }

        @Override
        public KnowledgeResourceProfile build() {
            if (_storedValue == null) {
                return this.init(new KnowledgeResourceProfile());
            } else {
                return ((KnowledgeResourceProfile) _storedValue);
            }
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="title" type="{}ST"/&gt;
     *         &lt;element name="profileDescription" type="{}ST"/&gt;
     *         &lt;element name="versionControl"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;attribute name="publicationDate" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "title",
        "profileDescription",
        "versionControl"
    })
    public static class Header {

        @XmlElement(required = true)
        protected String title;
        @XmlElement(required = true)
        protected String profileDescription;
        @XmlElement(required = true)
        protected KnowledgeResourceProfile.Header.VersionControl versionControl;
        @XmlAttribute(name = "id", required = true)
        protected BigInteger id;

        /**
         * Gets the value of the title property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTitle() {
            return title;
        }

        /**
         * Sets the value of the title property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTitle(String value) {
            this.title = value;
        }

        /**
         * Gets the value of the profileDescription property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProfileDescription() {
            return profileDescription;
        }

        /**
         * Sets the value of the profileDescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProfileDescription(String value) {
            this.profileDescription = value;
        }

        /**
         * Gets the value of the versionControl property.
         * 
         * @return
         *     possible object is
         *     {@link KnowledgeResourceProfile.Header.VersionControl }
         *     
         */
        public KnowledgeResourceProfile.Header.VersionControl getVersionControl() {
            return versionControl;
        }

        /**
         * Sets the value of the versionControl property.
         * 
         * @param value
         *     allowed object is
         *     {@link KnowledgeResourceProfile.Header.VersionControl }
         *     
         */
        public void setVersionControl(KnowledgeResourceProfile.Header.VersionControl value) {
            this.versionControl = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setId(BigInteger value) {
            this.id = value;
        }

        /**
         * Copies all state of this object to a builder. This method is used by the {@link #copyOf} method and should not be called directly by client code.
         * 
         * @param _other
         *     A builder instance to which the state of this object will be copied.
         */
        public<_B >void copyTo(final KnowledgeResourceProfile.Header.Builder<_B> _other) {
            _other.title = this.title;
            _other.profileDescription = this.profileDescription;
            _other.versionControl = ((this.versionControl == null)?null:this.versionControl.newCopyBuilder(_other));
            _other.id = this.id;
        }

        public<_B >KnowledgeResourceProfile.Header.Builder<_B> newCopyBuilder(final _B _parentBuilder) {
            return new KnowledgeResourceProfile.Header.Builder<_B>(_parentBuilder, this, true);
        }

        public KnowledgeResourceProfile.Header.Builder<Void> newCopyBuilder() {
            return newCopyBuilder(null);
        }

        public static KnowledgeResourceProfile.Header.Builder<Void> builder() {
            return new KnowledgeResourceProfile.Header.Builder<Void>(null, null, false);
        }

        public static<_B >KnowledgeResourceProfile.Header.Builder<_B> copyOf(final KnowledgeResourceProfile.Header _other) {
            final KnowledgeResourceProfile.Header.Builder<_B> _newBuilder = new KnowledgeResourceProfile.Header.Builder<_B>(null, null, false);
            _other.copyTo(_newBuilder);
            return _newBuilder;
        }

        /**
         * Copies all state of this object to a builder. This method is used by the {@link #copyOf} method and should not be called directly by client code.
         * 
         * @param _other
         *     A builder instance to which the state of this object will be copied.
         */
        public<_B >void copyTo(final KnowledgeResourceProfile.Header.Builder<_B> _other, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
            final PropertyTree titlePropertyTree = ((_propertyTree == null)?null:_propertyTree.get("title"));
            if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(titlePropertyTree!= null):((titlePropertyTree == null)||(!titlePropertyTree.isLeaf())))) {
                _other.title = this.title;
            }
            final PropertyTree profileDescriptionPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("profileDescription"));
            if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(profileDescriptionPropertyTree!= null):((profileDescriptionPropertyTree == null)||(!profileDescriptionPropertyTree.isLeaf())))) {
                _other.profileDescription = this.profileDescription;
            }
            final PropertyTree versionControlPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("versionControl"));
            if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(versionControlPropertyTree!= null):((versionControlPropertyTree == null)||(!versionControlPropertyTree.isLeaf())))) {
                _other.versionControl = ((this.versionControl == null)?null:this.versionControl.newCopyBuilder(_other, versionControlPropertyTree, _propertyTreeUse));
            }
            final PropertyTree idPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("id"));
            if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(idPropertyTree!= null):((idPropertyTree == null)||(!idPropertyTree.isLeaf())))) {
                _other.id = this.id;
            }
        }

        public<_B >KnowledgeResourceProfile.Header.Builder<_B> newCopyBuilder(final _B _parentBuilder, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
            return new KnowledgeResourceProfile.Header.Builder<_B>(_parentBuilder, this, true, _propertyTree, _propertyTreeUse);
        }

        public KnowledgeResourceProfile.Header.Builder<Void> newCopyBuilder(final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
            return newCopyBuilder(null, _propertyTree, _propertyTreeUse);
        }

        public static<_B >KnowledgeResourceProfile.Header.Builder<_B> copyOf(final KnowledgeResourceProfile.Header _other, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
            final KnowledgeResourceProfile.Header.Builder<_B> _newBuilder = new KnowledgeResourceProfile.Header.Builder<_B>(null, null, false);
            _other.copyTo(_newBuilder, _propertyTree, _propertyTreeUse);
            return _newBuilder;
        }

        public static KnowledgeResourceProfile.Header.Builder<Void> copyExcept(final KnowledgeResourceProfile.Header _other, final PropertyTree _propertyTree) {
            return copyOf(_other, _propertyTree, PropertyTreeUse.EXCLUDE);
        }

        public static KnowledgeResourceProfile.Header.Builder<Void> copyOnly(final KnowledgeResourceProfile.Header _other, final PropertyTree _propertyTree) {
            return copyOf(_other, _propertyTree, PropertyTreeUse.INCLUDE);
        }

        public static class Builder<_B >implements Buildable
        {

            protected final _B _parentBuilder;
            protected final KnowledgeResourceProfile.Header _storedValue;
            private String title;
            private String profileDescription;
            private KnowledgeResourceProfile.Header.VersionControl.Builder<KnowledgeResourceProfile.Header.Builder<_B>> versionControl;
            private BigInteger id;

            public Builder(final _B _parentBuilder, final KnowledgeResourceProfile.Header _other, final boolean _copy) {
                this._parentBuilder = _parentBuilder;
                if (_other!= null) {
                    if (_copy) {
                        _storedValue = null;
                        this.title = _other.title;
                        this.profileDescription = _other.profileDescription;
                        this.versionControl = ((_other.versionControl == null)?null:_other.versionControl.newCopyBuilder(this));
                        this.id = _other.id;
                    } else {
                        _storedValue = _other;
                    }
                } else {
                    _storedValue = null;
                }
            }

            public Builder(final _B _parentBuilder, final KnowledgeResourceProfile.Header _other, final boolean _copy, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
                this._parentBuilder = _parentBuilder;
                if (_other!= null) {
                    if (_copy) {
                        _storedValue = null;
                        final PropertyTree titlePropertyTree = ((_propertyTree == null)?null:_propertyTree.get("title"));
                        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(titlePropertyTree!= null):((titlePropertyTree == null)||(!titlePropertyTree.isLeaf())))) {
                            this.title = _other.title;
                        }
                        final PropertyTree profileDescriptionPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("profileDescription"));
                        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(profileDescriptionPropertyTree!= null):((profileDescriptionPropertyTree == null)||(!profileDescriptionPropertyTree.isLeaf())))) {
                            this.profileDescription = _other.profileDescription;
                        }
                        final PropertyTree versionControlPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("versionControl"));
                        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(versionControlPropertyTree!= null):((versionControlPropertyTree == null)||(!versionControlPropertyTree.isLeaf())))) {
                            this.versionControl = ((_other.versionControl == null)?null:_other.versionControl.newCopyBuilder(this, versionControlPropertyTree, _propertyTreeUse));
                        }
                        final PropertyTree idPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("id"));
                        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(idPropertyTree!= null):((idPropertyTree == null)||(!idPropertyTree.isLeaf())))) {
                            this.id = _other.id;
                        }
                    } else {
                        _storedValue = _other;
                    }
                } else {
                    _storedValue = null;
                }
            }

            public _B end() {
                return this._parentBuilder;
            }

            protected<_P extends KnowledgeResourceProfile.Header >_P init(final _P _product) {
                _product.title = this.title;
                _product.profileDescription = this.profileDescription;
                _product.versionControl = ((this.versionControl == null)?null:this.versionControl.build());
                _product.id = this.id;
                return _product;
            }

            /**
             * Sets the new value of "title" (any previous value will be replaced)
             * 
             * @param title
             *     New value of the "title" property.
             */
            public KnowledgeResourceProfile.Header.Builder<_B> withTitle(final String title) {
                this.title = title;
                return this;
            }

            /**
             * Sets the new value of "profileDescription" (any previous value will be replaced)
             * 
             * @param profileDescription
             *     New value of the "profileDescription" property.
             */
            public KnowledgeResourceProfile.Header.Builder<_B> withProfileDescription(final String profileDescription) {
                this.profileDescription = profileDescription;
                return this;
            }

            /**
             * Sets the new value of "versionControl" (any previous value will be replaced)
             * 
             * @param versionControl
             *     New value of the "versionControl" property.
             */
            public KnowledgeResourceProfile.Header.Builder<_B> withVersionControl(final KnowledgeResourceProfile.Header.VersionControl versionControl) {
                this.versionControl = ((versionControl == null)?null:new KnowledgeResourceProfile.Header.VersionControl.Builder<KnowledgeResourceProfile.Header.Builder<_B>>(this, versionControl, false));
                return this;
            }

            /**
             * Returns a new builder to build the value of the "versionControl" property (replacing previous value).
             * Use {@link org.openinfobutton.schemas.kb.KnowledgeResourceProfile.Header.VersionControl.Builder#end()} to return to the current builder.
             * 
             * @return
             *     A new builder to build the value of the "versionControl" property.
             *     Use {@link org.openinfobutton.schemas.kb.KnowledgeResourceProfile.Header.VersionControl.Builder#end()} to return to the current builder.
             */
            public KnowledgeResourceProfile.Header.VersionControl.Builder<? extends KnowledgeResourceProfile.Header.Builder<_B>> withVersionControl() {
                return this.versionControl = new KnowledgeResourceProfile.Header.VersionControl.Builder<KnowledgeResourceProfile.Header.Builder<_B>>(this, null, false);
            }

            /**
             * Sets the new value of "id" (any previous value will be replaced)
             * 
             * @param id
             *     New value of the "id" property.
             */
            public KnowledgeResourceProfile.Header.Builder<_B> withId(final BigInteger id) {
                this.id = id;
                return this;
            }

            @Override
            public KnowledgeResourceProfile.Header build() {
                if (_storedValue == null) {
                    return this.init(new KnowledgeResourceProfile.Header());
                } else {
                    return ((KnowledgeResourceProfile.Header) _storedValue);
                }
            }

        }

        public static class Select
            extends KnowledgeResourceProfile.Header.Selector<KnowledgeResourceProfile.Header.Select, Void>
        {


            Select() {
                super(null, null, null);
            }

            public static KnowledgeResourceProfile.Header.Select _root() {
                return new KnowledgeResourceProfile.Header.Select();
            }

        }

        public static class Selector<TRoot extends com.kscs.util.jaxb.Selector<TRoot, ?> , TParent >
            extends com.kscs.util.jaxb.Selector<TRoot, TParent>
        {

            private com.kscs.util.jaxb.Selector<TRoot, KnowledgeResourceProfile.Header.Selector<TRoot, TParent>> title = null;
            private com.kscs.util.jaxb.Selector<TRoot, KnowledgeResourceProfile.Header.Selector<TRoot, TParent>> profileDescription = null;
            private KnowledgeResourceProfile.Header.VersionControl.Selector<TRoot, KnowledgeResourceProfile.Header.Selector<TRoot, TParent>> versionControl = null;
            private com.kscs.util.jaxb.Selector<TRoot, KnowledgeResourceProfile.Header.Selector<TRoot, TParent>> id = null;

            public Selector(final TRoot root, final TParent parent, final String propertyName) {
                super(root, parent, propertyName);
            }

            @Override
            public Map<String, PropertyTree> buildChildren() {
                final Map<String, PropertyTree> products = new HashMap<String, PropertyTree>();
                products.putAll(super.buildChildren());
                if (this.title!= null) {
                    products.put("title", this.title.init());
                }
                if (this.profileDescription!= null) {
                    products.put("profileDescription", this.profileDescription.init());
                }
                if (this.versionControl!= null) {
                    products.put("versionControl", this.versionControl.init());
                }
                if (this.id!= null) {
                    products.put("id", this.id.init());
                }
                return products;
            }

            public com.kscs.util.jaxb.Selector<TRoot, KnowledgeResourceProfile.Header.Selector<TRoot, TParent>> title() {
                return ((this.title == null)?this.title = new com.kscs.util.jaxb.Selector<TRoot, KnowledgeResourceProfile.Header.Selector<TRoot, TParent>>(this._root, this, "title"):this.title);
            }

            public com.kscs.util.jaxb.Selector<TRoot, KnowledgeResourceProfile.Header.Selector<TRoot, TParent>> profileDescription() {
                return ((this.profileDescription == null)?this.profileDescription = new com.kscs.util.jaxb.Selector<TRoot, KnowledgeResourceProfile.Header.Selector<TRoot, TParent>>(this._root, this, "profileDescription"):this.profileDescription);
            }

            public KnowledgeResourceProfile.Header.VersionControl.Selector<TRoot, KnowledgeResourceProfile.Header.Selector<TRoot, TParent>> versionControl() {
                return ((this.versionControl == null)?this.versionControl = new KnowledgeResourceProfile.Header.VersionControl.Selector<TRoot, KnowledgeResourceProfile.Header.Selector<TRoot, TParent>>(this._root, this, "versionControl"):this.versionControl);
            }

            public com.kscs.util.jaxb.Selector<TRoot, KnowledgeResourceProfile.Header.Selector<TRoot, TParent>> id() {
                return ((this.id == null)?this.id = new com.kscs.util.jaxb.Selector<TRoot, KnowledgeResourceProfile.Header.Selector<TRoot, TParent>>(this._root, this, "id"):this.id);
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attribute name="publicationDate" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class VersionControl {

            @XmlAttribute(name = "publicationDate", required = true)
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar publicationDate;

            /**
             * Gets the value of the publicationDate property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getPublicationDate() {
                return publicationDate;
            }

            /**
             * Sets the value of the publicationDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setPublicationDate(XMLGregorianCalendar value) {
                this.publicationDate = value;
            }

            /**
             * Copies all state of this object to a builder. This method is used by the {@link #copyOf} method and should not be called directly by client code.
             * 
             * @param _other
             *     A builder instance to which the state of this object will be copied.
             */
            public<_B >void copyTo(final KnowledgeResourceProfile.Header.VersionControl.Builder<_B> _other) {
                _other.publicationDate = ((this.publicationDate == null)?null:((XMLGregorianCalendar) this.publicationDate.clone()));
            }

            public<_B >KnowledgeResourceProfile.Header.VersionControl.Builder<_B> newCopyBuilder(final _B _parentBuilder) {
                return new KnowledgeResourceProfile.Header.VersionControl.Builder<_B>(_parentBuilder, this, true);
            }

            public KnowledgeResourceProfile.Header.VersionControl.Builder<Void> newCopyBuilder() {
                return newCopyBuilder(null);
            }

            public static KnowledgeResourceProfile.Header.VersionControl.Builder<Void> builder() {
                return new KnowledgeResourceProfile.Header.VersionControl.Builder<Void>(null, null, false);
            }

            public static<_B >KnowledgeResourceProfile.Header.VersionControl.Builder<_B> copyOf(final KnowledgeResourceProfile.Header.VersionControl _other) {
                final KnowledgeResourceProfile.Header.VersionControl.Builder<_B> _newBuilder = new KnowledgeResourceProfile.Header.VersionControl.Builder<_B>(null, null, false);
                _other.copyTo(_newBuilder);
                return _newBuilder;
            }

            /**
             * Copies all state of this object to a builder. This method is used by the {@link #copyOf} method and should not be called directly by client code.
             * 
             * @param _other
             *     A builder instance to which the state of this object will be copied.
             */
            public<_B >void copyTo(final KnowledgeResourceProfile.Header.VersionControl.Builder<_B> _other, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
                final PropertyTree publicationDatePropertyTree = ((_propertyTree == null)?null:_propertyTree.get("publicationDate"));
                if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(publicationDatePropertyTree!= null):((publicationDatePropertyTree == null)||(!publicationDatePropertyTree.isLeaf())))) {
                    _other.publicationDate = ((this.publicationDate == null)?null:((XMLGregorianCalendar) this.publicationDate.clone()));
                }
            }

            public<_B >KnowledgeResourceProfile.Header.VersionControl.Builder<_B> newCopyBuilder(final _B _parentBuilder, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
                return new KnowledgeResourceProfile.Header.VersionControl.Builder<_B>(_parentBuilder, this, true, _propertyTree, _propertyTreeUse);
            }

            public KnowledgeResourceProfile.Header.VersionControl.Builder<Void> newCopyBuilder(final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
                return newCopyBuilder(null, _propertyTree, _propertyTreeUse);
            }

            public static<_B >KnowledgeResourceProfile.Header.VersionControl.Builder<_B> copyOf(final KnowledgeResourceProfile.Header.VersionControl _other, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
                final KnowledgeResourceProfile.Header.VersionControl.Builder<_B> _newBuilder = new KnowledgeResourceProfile.Header.VersionControl.Builder<_B>(null, null, false);
                _other.copyTo(_newBuilder, _propertyTree, _propertyTreeUse);
                return _newBuilder;
            }

            public static KnowledgeResourceProfile.Header.VersionControl.Builder<Void> copyExcept(final KnowledgeResourceProfile.Header.VersionControl _other, final PropertyTree _propertyTree) {
                return copyOf(_other, _propertyTree, PropertyTreeUse.EXCLUDE);
            }

            public static KnowledgeResourceProfile.Header.VersionControl.Builder<Void> copyOnly(final KnowledgeResourceProfile.Header.VersionControl _other, final PropertyTree _propertyTree) {
                return copyOf(_other, _propertyTree, PropertyTreeUse.INCLUDE);
            }

            public static class Builder<_B >implements Buildable
            {

                protected final _B _parentBuilder;
                protected final KnowledgeResourceProfile.Header.VersionControl _storedValue;
                private XMLGregorianCalendar publicationDate;

                public Builder(final _B _parentBuilder, final KnowledgeResourceProfile.Header.VersionControl _other, final boolean _copy) {
                    this._parentBuilder = _parentBuilder;
                    if (_other!= null) {
                        if (_copy) {
                            _storedValue = null;
                            this.publicationDate = ((_other.publicationDate == null)?null:((XMLGregorianCalendar) _other.publicationDate.clone()));
                        } else {
                            _storedValue = _other;
                        }
                    } else {
                        _storedValue = null;
                    }
                }

                public Builder(final _B _parentBuilder, final KnowledgeResourceProfile.Header.VersionControl _other, final boolean _copy, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
                    this._parentBuilder = _parentBuilder;
                    if (_other!= null) {
                        if (_copy) {
                            _storedValue = null;
                            final PropertyTree publicationDatePropertyTree = ((_propertyTree == null)?null:_propertyTree.get("publicationDate"));
                            if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(publicationDatePropertyTree!= null):((publicationDatePropertyTree == null)||(!publicationDatePropertyTree.isLeaf())))) {
                                this.publicationDate = ((_other.publicationDate == null)?null:((XMLGregorianCalendar) _other.publicationDate.clone()));
                            }
                        } else {
                            _storedValue = _other;
                        }
                    } else {
                        _storedValue = null;
                    }
                }

                public _B end() {
                    return this._parentBuilder;
                }

                protected<_P extends KnowledgeResourceProfile.Header.VersionControl >_P init(final _P _product) {
                    _product.publicationDate = this.publicationDate;
                    return _product;
                }

                /**
                 * Sets the new value of "publicationDate" (any previous value will be replaced)
                 * 
                 * @param publicationDate
                 *     New value of the "publicationDate" property.
                 */
                public KnowledgeResourceProfile.Header.VersionControl.Builder<_B> withPublicationDate(final XMLGregorianCalendar publicationDate) {
                    this.publicationDate = publicationDate;
                    return this;
                }

                @Override
                public KnowledgeResourceProfile.Header.VersionControl build() {
                    if (_storedValue == null) {
                        return this.init(new KnowledgeResourceProfile.Header.VersionControl());
                    } else {
                        return ((KnowledgeResourceProfile.Header.VersionControl) _storedValue);
                    }
                }

            }

            public static class Select
                extends KnowledgeResourceProfile.Header.VersionControl.Selector<KnowledgeResourceProfile.Header.VersionControl.Select, Void>
            {


                Select() {
                    super(null, null, null);
                }

                public static KnowledgeResourceProfile.Header.VersionControl.Select _root() {
                    return new KnowledgeResourceProfile.Header.VersionControl.Select();
                }

            }

            public static class Selector<TRoot extends com.kscs.util.jaxb.Selector<TRoot, ?> , TParent >
                extends com.kscs.util.jaxb.Selector<TRoot, TParent>
            {

                private com.kscs.util.jaxb.Selector<TRoot, KnowledgeResourceProfile.Header.VersionControl.Selector<TRoot, TParent>> publicationDate = null;

                public Selector(final TRoot root, final TParent parent, final String propertyName) {
                    super(root, parent, propertyName);
                }

                @Override
                public Map<String, PropertyTree> buildChildren() {
                    final Map<String, PropertyTree> products = new HashMap<String, PropertyTree>();
                    products.putAll(super.buildChildren());
                    if (this.publicationDate!= null) {
                        products.put("publicationDate", this.publicationDate.init());
                    }
                    return products;
                }

                public com.kscs.util.jaxb.Selector<TRoot, KnowledgeResourceProfile.Header.VersionControl.Selector<TRoot, TParent>> publicationDate() {
                    return ((this.publicationDate == null)?this.publicationDate = new com.kscs.util.jaxb.Selector<TRoot, KnowledgeResourceProfile.Header.VersionControl.Selector<TRoot, TParent>>(this._root, this, "publicationDate"):this.publicationDate);
                }

            }

        }

    }

    public static class Select
        extends KnowledgeResourceProfile.Selector<KnowledgeResourceProfile.Select, Void>
    {


        Select() {
            super(null, null, null);
        }

        public static KnowledgeResourceProfile.Select _root() {
            return new KnowledgeResourceProfile.Select();
        }

    }

    public static class Selector<TRoot extends com.kscs.util.jaxb.Selector<TRoot, ?> , TParent >
        extends com.kscs.util.jaxb.Selector<TRoot, TParent>
    {

        private KnowledgeResourceProfile.Header.Selector<TRoot, KnowledgeResourceProfile.Selector<TRoot, TParent>> header = null;
        private ProfileDefinition.Selector<TRoot, KnowledgeResourceProfile.Selector<TRoot, TParent>> profileDefinition = null;

        public Selector(final TRoot root, final TParent parent, final String propertyName) {
            super(root, parent, propertyName);
        }

        @Override
        public Map<String, PropertyTree> buildChildren() {
            final Map<String, PropertyTree> products = new HashMap<String, PropertyTree>();
            products.putAll(super.buildChildren());
            if (this.header!= null) {
                products.put("header", this.header.init());
            }
            if (this.profileDefinition!= null) {
                products.put("profileDefinition", this.profileDefinition.init());
            }
            return products;
        }

        public KnowledgeResourceProfile.Header.Selector<TRoot, KnowledgeResourceProfile.Selector<TRoot, TParent>> header() {
            return ((this.header == null)?this.header = new KnowledgeResourceProfile.Header.Selector<TRoot, KnowledgeResourceProfile.Selector<TRoot, TParent>>(this._root, this, "header"):this.header);
        }

        public ProfileDefinition.Selector<TRoot, KnowledgeResourceProfile.Selector<TRoot, TParent>> profileDefinition() {
            return ((this.profileDefinition == null)?this.profileDefinition = new ProfileDefinition.Selector<TRoot, KnowledgeResourceProfile.Selector<TRoot, TParent>>(this._root, this, "profileDefinition"):this.profileDefinition);
        }

    }

}
