//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.02 at 12:23:52 PM MST 
//


package org.openinfobutton.schemas.kb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.openinfobutton.schemas.kb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PatientGender_QNAME = new QName("", "patientGender");
    private final static QName _PatientAgeGroup_QNAME = new QName("", "patientAgeGroup");
    private final static QName _Task_QNAME = new QName("", "task");
    private final static QName _ServiceDeliveryLocation_QNAME = new QName("", "serviceDeliveryLocation");
    private final static QName _EncounterType_QNAME = new QName("", "encounterType");
    private final static QName _PerformerLanguage_QNAME = new QName("", "performerLanguage");
    private final static QName _PerformerDiscipline_QNAME = new QName("", "performerDiscipline");
    private final static QName _PerformerKnowledgeUserType_QNAME = new QName("", "performerKnowledgeUserType");
    private final static QName _InformationRecipientLanguage_QNAME = new QName("", "informationRecipientLanguage");
    private final static QName _InformationRecipientDiscipline_QNAME = new QName("", "informationRecipientDiscipline");
    private final static QName _InformationRecipientUserType_QNAME = new QName("", "informationRecipientUserType");
    private final static QName _ConceptOfInterest_QNAME = new QName("", "conceptOfInterest");
    private final static QName _SubTopic_QNAME = new QName("", "subTopic");
    private final static QName _SemanticTypes_QNAME = new QName("", "semanticTypes");
    private final static QName _ValueSet_QNAME = new QName("", "valueSet");
    private final static QName _EMail_QNAME = new QName("", "eMail");
    private final static QName _Phone_QNAME = new QName("", "phone");
    private final static QName _Description_QNAME = new QName("", "description");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.openinfobutton.schemas.kb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link KnowledgeResourceProfile }
     * 
     */
    public KnowledgeResourceProfile createKnowledgeResourceProfile() {
        return new KnowledgeResourceProfile();
    }

    /**
     * Create an instance of {@link TerminologyInference }
     * 
     */
    public TerminologyInference createTerminologyInference() {
        return new TerminologyInference();
    }

    /**
     * Create an instance of {@link KnowledgeRequestService }
     * 
     */
    public KnowledgeRequestService createKnowledgeRequestService() {
        return new KnowledgeRequestService();
    }

    /**
     * Create an instance of {@link ConstraintDefinition }
     * 
     */
    public ConstraintDefinition createConstraintDefinition() {
        return new ConstraintDefinition();
    }

    /**
     * Create an instance of {@link Context }
     * 
     */
    public Context createContext() {
        return new Context();
    }

    /**
     * Create an instance of {@link KnowledgeRequestService.Attributes }
     * 
     */
    public KnowledgeRequestService.Attributes createKnowledgeRequestServiceAttributes() {
        return new KnowledgeRequestService.Attributes();
    }

    /**
     * Create an instance of {@link TerminologyInference.CodeInference }
     * 
     */
    public TerminologyInference.CodeInference createTerminologyInferenceCodeInference() {
        return new TerminologyInference.CodeInference();
    }

    /**
     * Create an instance of {@link TerminologyInference.CodeInference.InferenceDefinition }
     * 
     */
    public TerminologyInference.CodeInference.InferenceDefinition createTerminologyInferenceCodeInferenceInferenceDefinition() {
        return new TerminologyInference.CodeInference.InferenceDefinition();
    }

    /**
     * Create an instance of {@link TerminologyInference.CodeInference.InferenceDefinition.ExternalDefinition }
     * 
     */
    public TerminologyInference.CodeInference.InferenceDefinition.ExternalDefinition createTerminologyInferenceCodeInferenceInferenceDefinitionExternalDefinition() {
        return new TerminologyInference.CodeInference.InferenceDefinition.ExternalDefinition();
    }

    /**
     * Create an instance of {@link TerminologyInference.CodeInference.InferenceDefinition.LocalMappings }
     * 
     */
    public TerminologyInference.CodeInference.InferenceDefinition.LocalMappings createTerminologyInferenceCodeInferenceInferenceDefinitionLocalMappings() {
        return new TerminologyInference.CodeInference.InferenceDefinition.LocalMappings();
    }

    /**
     * Create an instance of {@link SubTopic }
     * 
     */
    public SubTopic createSubTopic() {
        return new SubTopic();
    }

    /**
     * Create an instance of {@link SubTopic.SearchParameter }
     * 
     */
    public SubTopic.SearchParameter createSubTopicSearchParameter() {
        return new SubTopic.SearchParameter();
    }

    /**
     * Create an instance of {@link CodedContextElement }
     * 
     */
    public CodedContextElement createCodedContextElement() {
        return new CodedContextElement();
    }

    /**
     * Create an instance of {@link CodedContextElement.MatchingDomain }
     * 
     */
    public CodedContextElement.MatchingDomain createCodedContextElementMatchingDomain() {
        return new CodedContextElement.MatchingDomain();
    }

    /**
     * Create an instance of {@link ProfileDefinition }
     * 
     */
    public ProfileDefinition createProfileDefinition() {
        return new ProfileDefinition();
    }

    /**
     * Create an instance of {@link ProfileDefinition.AuthorizedOrganizations }
     * 
     */
    public ProfileDefinition.AuthorizedOrganizations createProfileDefinitionAuthorizedOrganizations() {
        return new ProfileDefinition.AuthorizedOrganizations();
    }

    /**
     * Create an instance of {@link ProfileDefinition.AuthorizedOrganizations.AuthorizedOrganization }
     * 
     */
    public ProfileDefinition.AuthorizedOrganizations.AuthorizedOrganization createProfileDefinitionAuthorizedOrganizationsAuthorizedOrganization() {
        return new ProfileDefinition.AuthorizedOrganizations.AuthorizedOrganization();
    }

    /**
     * Create an instance of {@link ProfileDefinition.AuthorizedOrganizations.AuthorizedOrganization.AccessMethod }
     * 
     */
    public ProfileDefinition.AuthorizedOrganizations.AuthorizedOrganization.AccessMethod createProfileDefinitionAuthorizedOrganizationsAuthorizedOrganizationAccessMethod() {
        return new ProfileDefinition.AuthorizedOrganizations.AuthorizedOrganization.AccessMethod();
    }

    /**
     * Create an instance of {@link ProfileDefinition.AuthorizedOrganizations.AuthorizedOrganization.AccessMethod.AuthenticationMethod }
     * 
     */
    public ProfileDefinition.AuthorizedOrganizations.AuthorizedOrganization.AccessMethod.AuthenticationMethod createProfileDefinitionAuthorizedOrganizationsAuthorizedOrganizationAccessMethodAuthenticationMethod() {
        return new ProfileDefinition.AuthorizedOrganizations.AuthorizedOrganization.AccessMethod.AuthenticationMethod();
    }

    /**
     * Create an instance of {@link KnowledgeResourceProfile.Header }
     * 
     */
    public KnowledgeResourceProfile.Header createKnowledgeResourceProfileHeader() {
        return new KnowledgeResourceProfile.Header();
    }

    /**
     * Create an instance of {@link Id }
     * 
     */
    public Id createId() {
        return new Id();
    }

    /**
     * Create an instance of {@link SyntaxOnResource }
     * 
     */
    public SyntaxOnResource createSyntaxOnResource() {
        return new SyntaxOnResource();
    }

    /**
     * Create an instance of {@link CDset }
     * 
     */
    public CDset createCDset() {
        return new CDset();
    }

    /**
     * Create an instance of {@link SubTopics }
     * 
     */
    public SubTopics createSubTopics() {
        return new SubTopics();
    }

    /**
     * Create an instance of {@link CD }
     * 
     */
    public CD createCD() {
        return new CD();
    }

    /**
     * Create an instance of {@link ContactInformation }
     * 
     */
    public ContactInformation createContactInformation() {
        return new ContactInformation();
    }

    /**
     * Create an instance of {@link Name }
     * 
     */
    public Name createName() {
        return new Name();
    }

    /**
     * Create an instance of {@link TerminologyInference.KeywordInference }
     * 
     */
    public TerminologyInference.KeywordInference createTerminologyInferenceKeywordInference() {
        return new TerminologyInference.KeywordInference();
    }

    /**
     * Create an instance of {@link Code }
     * 
     */
    public Code createCode() {
        return new Code();
    }

    /**
     * Create an instance of {@link KnowledgeRequestServiceLocation }
     * 
     */
    public KnowledgeRequestServiceLocation createKnowledgeRequestServiceLocation() {
        return new KnowledgeRequestServiceLocation();
    }

    /**
     * Create an instance of {@link KnowledgeUser }
     * 
     */
    public KnowledgeUser createKnowledgeUser() {
        return new KnowledgeUser();
    }

    /**
     * Create an instance of {@link ContactType }
     * 
     */
    public ContactType createContactType() {
        return new ContactType();
    }

    /**
     * Create an instance of {@link PQ }
     * 
     */
    public PQ createPQ() {
        return new PQ();
    }

    /**
     * Create an instance of {@link ConstraintDefinition.Constraint }
     * 
     */
    public ConstraintDefinition.Constraint createConstraintDefinitionConstraint() {
        return new ConstraintDefinition.Constraint();
    }

    /**
     * Create an instance of {@link Context.ContextDefinition }
     * 
     */
    public Context.ContextDefinition createContextContextDefinition() {
        return new Context.ContextDefinition();
    }

    /**
     * Create an instance of {@link KnowledgeRequestService.Attributes.Attribute }
     * 
     */
    public KnowledgeRequestService.Attributes.Attribute createKnowledgeRequestServiceAttributesAttribute() {
        return new KnowledgeRequestService.Attributes.Attribute();
    }

    /**
     * Create an instance of {@link TerminologyInference.CodeInference.InferenceDefinition.ExternalDefinition.TraverseAssociation }
     * 
     */
    public TerminologyInference.CodeInference.InferenceDefinition.ExternalDefinition.TraverseAssociation createTerminologyInferenceCodeInferenceInferenceDefinitionExternalDefinitionTraverseAssociation() {
        return new TerminologyInference.CodeInference.InferenceDefinition.ExternalDefinition.TraverseAssociation();
    }

    /**
     * Create an instance of {@link TerminologyInference.CodeInference.InferenceDefinition.LocalMappings.Mapping }
     * 
     */
    public TerminologyInference.CodeInference.InferenceDefinition.LocalMappings.Mapping createTerminologyInferenceCodeInferenceInferenceDefinitionLocalMappingsMapping() {
        return new TerminologyInference.CodeInference.InferenceDefinition.LocalMappings.Mapping();
    }

    /**
     * Create an instance of {@link SubTopic.SearchParameter.ValueSource }
     * 
     */
    public SubTopic.SearchParameter.ValueSource createSubTopicSearchParameterValueSource() {
        return new SubTopic.SearchParameter.ValueSource();
    }

    /**
     * Create an instance of {@link CodedContextElement.SearchParameter }
     * 
     */
    public CodedContextElement.SearchParameter createCodedContextElementSearchParameter() {
        return new CodedContextElement.SearchParameter();
    }

    /**
     * Create an instance of {@link CodedContextElement.MatchingDomain.Enumeration }
     * 
     */
    public CodedContextElement.MatchingDomain.Enumeration createCodedContextElementMatchingDomainEnumeration() {
        return new CodedContextElement.MatchingDomain.Enumeration();
    }

    /**
     * Create an instance of {@link ProfileDefinition.SupportedTerminologies }
     * 
     */
    public ProfileDefinition.SupportedTerminologies createProfileDefinitionSupportedTerminologies() {
        return new ProfileDefinition.SupportedTerminologies();
    }

    /**
     * Create an instance of {@link ProfileDefinition.Contexts }
     * 
     */
    public ProfileDefinition.Contexts createProfileDefinitionContexts() {
        return new ProfileDefinition.Contexts();
    }

    /**
     * Create an instance of {@link ProfileDefinition.AuthorizedOrganizations.AuthorizedOrganization.AccessMethod.AuthenticationMethod.Ip }
     * 
     */
    public ProfileDefinition.AuthorizedOrganizations.AuthorizedOrganization.AccessMethod.AuthenticationMethod.Ip createProfileDefinitionAuthorizedOrganizationsAuthorizedOrganizationAccessMethodAuthenticationMethodIp() {
        return new ProfileDefinition.AuthorizedOrganizations.AuthorizedOrganization.AccessMethod.AuthenticationMethod.Ip();
    }

    /**
     * Create an instance of {@link ProfileDefinition.AuthorizedOrganizations.AuthorizedOrganization.AccessMethod.AuthenticationMethod.UsrPwd }
     * 
     */
    public ProfileDefinition.AuthorizedOrganizations.AuthorizedOrganization.AccessMethod.AuthenticationMethod.UsrPwd createProfileDefinitionAuthorizedOrganizationsAuthorizedOrganizationAccessMethodAuthenticationMethodUsrPwd() {
        return new ProfileDefinition.AuthorizedOrganizations.AuthorizedOrganization.AccessMethod.AuthenticationMethod.UsrPwd();
    }

    /**
     * Create an instance of {@link KnowledgeResourceProfile.Header.VersionControl }
     * 
     */
    public KnowledgeResourceProfile.Header.VersionControl createKnowledgeResourceProfileHeaderVersionControl() {
        return new KnowledgeResourceProfile.Header.VersionControl();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CodedContextElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "patientGender")
    public JAXBElement<CodedContextElement> createPatientGender(CodedContextElement value) {
        return new JAXBElement<CodedContextElement>(_PatientGender_QNAME, CodedContextElement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CodedContextElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "patientAgeGroup")
    public JAXBElement<CodedContextElement> createPatientAgeGroup(CodedContextElement value) {
        return new JAXBElement<CodedContextElement>(_PatientAgeGroup_QNAME, CodedContextElement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CodedContextElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "task")
    public JAXBElement<CodedContextElement> createTask(CodedContextElement value) {
        return new JAXBElement<CodedContextElement>(_Task_QNAME, CodedContextElement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Id }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "serviceDeliveryLocation")
    public JAXBElement<Id> createServiceDeliveryLocation(Id value) {
        return new JAXBElement<Id>(_ServiceDeliveryLocation_QNAME, Id.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CodedContextElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "encounterType")
    public JAXBElement<CodedContextElement> createEncounterType(CodedContextElement value) {
        return new JAXBElement<CodedContextElement>(_EncounterType_QNAME, CodedContextElement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CodedContextElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "performerLanguage")
    public JAXBElement<CodedContextElement> createPerformerLanguage(CodedContextElement value) {
        return new JAXBElement<CodedContextElement>(_PerformerLanguage_QNAME, CodedContextElement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CodedContextElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "performerDiscipline")
    public JAXBElement<CodedContextElement> createPerformerDiscipline(CodedContextElement value) {
        return new JAXBElement<CodedContextElement>(_PerformerDiscipline_QNAME, CodedContextElement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CodedContextElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "performerKnowledgeUserType")
    public JAXBElement<CodedContextElement> createPerformerKnowledgeUserType(CodedContextElement value) {
        return new JAXBElement<CodedContextElement>(_PerformerKnowledgeUserType_QNAME, CodedContextElement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CodedContextElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "informationRecipientLanguage")
    public JAXBElement<CodedContextElement> createInformationRecipientLanguage(CodedContextElement value) {
        return new JAXBElement<CodedContextElement>(_InformationRecipientLanguage_QNAME, CodedContextElement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CodedContextElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "informationRecipientDiscipline")
    public JAXBElement<CodedContextElement> createInformationRecipientDiscipline(CodedContextElement value) {
        return new JAXBElement<CodedContextElement>(_InformationRecipientDiscipline_QNAME, CodedContextElement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CodedContextElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "informationRecipientUserType")
    public JAXBElement<CodedContextElement> createInformationRecipientUserType(CodedContextElement value) {
        return new JAXBElement<CodedContextElement>(_InformationRecipientUserType_QNAME, CodedContextElement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CodedContextElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "conceptOfInterest")
    public JAXBElement<CodedContextElement> createConceptOfInterest(CodedContextElement value) {
        return new JAXBElement<CodedContextElement>(_ConceptOfInterest_QNAME, CodedContextElement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SubTopic }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "subTopic")
    public JAXBElement<SubTopic> createSubTopic(SubTopic value) {
        return new JAXBElement<SubTopic>(_SubTopic_QNAME, SubTopic.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CDset }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "semanticTypes")
    public JAXBElement<CDset> createSemanticTypes(CDset value) {
        return new JAXBElement<CDset>(_SemanticTypes_QNAME, CDset.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CD }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "valueSet")
    public JAXBElement<CD> createValueSet(CD value) {
        return new JAXBElement<CD>(_ValueSet_QNAME, CD.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "eMail")
    public JAXBElement<String> createEMail(String value) {
        return new JAXBElement<String>(_EMail_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "phone")
    public JAXBElement<String> createPhone(String value) {
        return new JAXBElement<String>(_Phone_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "description")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, String.class, null, value);
    }

}
