//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.31 at 02:20:37 PM MDT 
//


package org.hl7.v3;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for REDS_MT010001UV.Encounter complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="REDS_MT010001UV.Encounter">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="code" type="{}CD.Lite" minOccurs="0" form="qualified"/>
 *         &lt;element name="serviceDeliveryLocation" type="{}REDS_MT010001UV.ServiceDeliveryLocation" minOccurs="0" form="qualified"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "REDS_MT010001UV.Encounter", propOrder = {
    "code",
    "serviceDeliveryLocation"
})
public class REDSMT010001UVEncounter {

    protected CDLite code;
    @XmlElementRef(name = "serviceDeliveryLocation", type = JAXBElement.class)
    protected JAXBElement<REDSMT010001UVServiceDeliveryLocation> serviceDeliveryLocation;

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link CDLite }
     *     
     */
    public CDLite getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link CDLite }
     *     
     */
    public void setCode(CDLite value) {
        this.code = value;
    }

    /**
     * Gets the value of the serviceDeliveryLocation property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link REDSMT010001UVServiceDeliveryLocation }{@code >}
     *     
     */
    public JAXBElement<REDSMT010001UVServiceDeliveryLocation> getServiceDeliveryLocation() {
        return serviceDeliveryLocation;
    }

    /**
     * Sets the value of the serviceDeliveryLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link REDSMT010001UVServiceDeliveryLocation }{@code >}
     *     
     */
    public void setServiceDeliveryLocation(JAXBElement<REDSMT010001UVServiceDeliveryLocation> value) {
        this.serviceDeliveryLocation = ((JAXBElement<REDSMT010001UVServiceDeliveryLocation> ) value);
    }

}
