//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.31 at 02:20:37 PM MDT 
//


package org.hl7.v3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for REDS_MT010001UV.PatientContext complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="REDS_MT010001UV.PatientContext">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="administrativeGenderCode" type="{}CD.Lite" minOccurs="0" form="qualified"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="age" type="{}REDS_MT010001UV.Age" form="qualified"/>
 *           &lt;element name="ageGroup" type="{}REDS_MT010001UV.AgeGroup" form="qualified"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "REDS_MT010001UV.PatientContext", propOrder = {
    "administrativeGenderCode",
    "ageOrAgeGroup"
})
public class REDSMT010001UVPatientContext {

    protected CDLite administrativeGenderCode;
    @XmlElements({
        @XmlElement(name = "age", type = REDSMT010001UVAge.class, nillable = true),
        @XmlElement(name = "ageGroup", type = REDSMT010001UVAgeGroup.class, nillable = true)
    })
    protected List<Object> ageOrAgeGroup;

    /**
     * Gets the value of the administrativeGenderCode property.
     * 
     * @return
     *     possible object is
     *     {@link CDLite }
     *     
     */
    public CDLite getAdministrativeGenderCode() {
        return administrativeGenderCode;
    }

    /**
     * Sets the value of the administrativeGenderCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CDLite }
     *     
     */
    public void setAdministrativeGenderCode(CDLite value) {
        this.administrativeGenderCode = value;
    }

    /**
     * Gets the value of the ageOrAgeGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ageOrAgeGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAgeOrAgeGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link REDSMT010001UVAge }
     * {@link REDSMT010001UVAgeGroup }
     * 
     * 
     */
    public List<Object> getAgeOrAgeGroup() {
        if (ageOrAgeGroup == null) {
            ageOrAgeGroup = new ArrayList<Object>();
        }
        return this.ageOrAgeGroup;
    }

}
