
package gov.nih.nlm.uts.webservice.semnet;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UtsWsSemanticNetworkController", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UtsWsSemanticNetworkController {


    /**
     * 
     * @param semanticTypeId
     * @param ticket
     * @param version
     * @return
     *     returns gov.nih.nlm.uts.webservice.semnet.SemanticTypeDTO
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSemanticType", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.semnet.GetSemanticType")
    @ResponseWrapper(localName = "getSemanticTypeResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.semnet.GetSemanticTypeResponse")
    public SemanticTypeDTO getSemanticType(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "semanticTypeId", targetNamespace = "")
        String semanticTypeId)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param semanticTypeId
     * @param ticket
     * @param version
     * @return
     *     returns gov.nih.nlm.uts.webservice.semnet.SemanticNetworkRelationLabelDTO
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSemanticNetworkRelationLabel", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.semnet.GetSemanticNetworkRelationLabel")
    @ResponseWrapper(localName = "getSemanticNetworkRelationLabelResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.semnet.GetSemanticNetworkRelationLabelResponse")
    public SemanticNetworkRelationLabelDTO getSemanticNetworkRelationLabel(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "semanticTypeId", targetNamespace = "")
        String semanticTypeId)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param semanticTypeId
     * @param ticket
     * @param version
     * @return
     *     returns java.util.List<gov.nih.nlm.uts.webservice.semnet.SemanticTypeRelationDTO>
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getInheritedSemanticTypeRelations", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.semnet.GetInheritedSemanticTypeRelations")
    @ResponseWrapper(localName = "getInheritedSemanticTypeRelationsResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.semnet.GetInheritedSemanticTypeRelationsResponse")
    public List<SemanticTypeRelationDTO> getInheritedSemanticTypeRelations(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "semanticTypeId", targetNamespace = "")
        String semanticTypeId)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param semanticTypeId
     * @param ticket
     * @param version
     * @return
     *     returns java.util.List<gov.nih.nlm.uts.webservice.semnet.SemanticNetworkRelationLabelRelationDTO>
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getInheritedSemanticNetworkRelationLabelRelations", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.semnet.GetInheritedSemanticNetworkRelationLabelRelations")
    @ResponseWrapper(localName = "getInheritedSemanticNetworkRelationLabelRelationsResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.semnet.GetInheritedSemanticNetworkRelationLabelRelationsResponse")
    public List<SemanticNetworkRelationLabelRelationDTO> getInheritedSemanticNetworkRelationLabelRelations(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "semanticTypeId", targetNamespace = "")
        String semanticTypeId)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @param version
     * @return
     *     returns java.util.List<gov.nih.nlm.uts.webservice.semnet.SemanticTypeRelationDTO>
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllSemanticTypeRelations", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.semnet.GetAllSemanticTypeRelations")
    @ResponseWrapper(localName = "getAllSemanticTypeRelationsResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.semnet.GetAllSemanticTypeRelationsResponse")
    public List<SemanticTypeRelationDTO> getAllSemanticTypeRelations(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param semanticTypeId
     * @param ticket
     * @param version
     * @return
     *     returns java.util.List<gov.nih.nlm.uts.webservice.semnet.SemanticNetworkRelationLabelRelationDTO>
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getInverseInheritedSemanticNetworkRelationLabelRelations", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.semnet.GetInverseInheritedSemanticNetworkRelationLabelRelations")
    @ResponseWrapper(localName = "getInverseInheritedSemanticNetworkRelationLabelRelationsResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.semnet.GetInverseInheritedSemanticNetworkRelationLabelRelationsResponse")
    public List<SemanticNetworkRelationLabelRelationDTO> getInverseInheritedSemanticNetworkRelationLabelRelations(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "semanticTypeId", targetNamespace = "")
        String semanticTypeId)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param semanticTypeId
     * @param ticket
     * @param version
     * @return
     *     returns java.util.List<gov.nih.nlm.uts.webservice.semnet.SemanticTypeRelationDTO>
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getInverseInheritedSemanticTypeRelations", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.semnet.GetInverseInheritedSemanticTypeRelations")
    @ResponseWrapper(localName = "getInverseInheritedSemanticTypeRelationsResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.semnet.GetInverseInheritedSemanticTypeRelationsResponse")
    public List<SemanticTypeRelationDTO> getInverseInheritedSemanticTypeRelations(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "semanticTypeId", targetNamespace = "")
        String semanticTypeId)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param semanticTypeId
     * @param ticket
     * @param version
     * @return
     *     returns java.util.List<gov.nih.nlm.uts.webservice.semnet.SemanticNetworkRelationLabelRelationDTO>
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getInverseSemanticNetworkRelationLabelRelations", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.semnet.GetInverseSemanticNetworkRelationLabelRelations")
    @ResponseWrapper(localName = "getInverseSemanticNetworkRelationLabelRelationsResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.semnet.GetInverseSemanticNetworkRelationLabelRelationsResponse")
    public List<SemanticNetworkRelationLabelRelationDTO> getInverseSemanticNetworkRelationLabelRelations(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "semanticTypeId", targetNamespace = "")
        String semanticTypeId)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param semanticTypeId
     * @param ticket
     * @param version
     * @return
     *     returns java.util.List<gov.nih.nlm.uts.webservice.semnet.SemanticTypeRelationDTO>
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getInverseSemanticTypeRelations", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.semnet.GetInverseSemanticTypeRelations")
    @ResponseWrapper(localName = "getInverseSemanticTypeRelationsResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.semnet.GetInverseSemanticTypeRelationsResponse")
    public List<SemanticTypeRelationDTO> getInverseSemanticTypeRelations(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "semanticTypeId", targetNamespace = "")
        String semanticTypeId)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param semanticTypeId
     * @param semanticRelationLabelId
     * @param relatedSemanticTypeId
     * @param ticket
     * @param version
     * @return
     *     returns gov.nih.nlm.uts.webservice.semnet.SemanticNetworkRelationLabelRelationDTO
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSemanticNetworkRelationLabelRelation", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.semnet.GetSemanticNetworkRelationLabelRelation")
    @ResponseWrapper(localName = "getSemanticNetworkRelationLabelRelationResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.semnet.GetSemanticNetworkRelationLabelRelationResponse")
    public SemanticNetworkRelationLabelRelationDTO getSemanticNetworkRelationLabelRelation(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "semanticTypeId", targetNamespace = "")
        String semanticTypeId,
        @WebParam(name = "semanticRelationLabelId", targetNamespace = "")
        String semanticRelationLabelId,
        @WebParam(name = "relatedSemanticTypeId", targetNamespace = "")
        String relatedSemanticTypeId)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param semanticTypeId
     * @param ticket
     * @param version
     * @return
     *     returns java.util.List<gov.nih.nlm.uts.webservice.semnet.SemanticNetworkRelationLabelRelationDTO>
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSemanticNetworkRelationLabelRelations", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.semnet.GetSemanticNetworkRelationLabelRelations")
    @ResponseWrapper(localName = "getSemanticNetworkRelationLabelRelationsResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.semnet.GetSemanticNetworkRelationLabelRelationsResponse")
    public List<SemanticNetworkRelationLabelRelationDTO> getSemanticNetworkRelationLabelRelations(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "semanticTypeId", targetNamespace = "")
        String semanticTypeId)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param semanticTypeId
     * @param relatedSemanticTypeId
     * @param ticket
     * @param version
     * @return
     *     returns java.util.List<gov.nih.nlm.uts.webservice.semnet.SemanticNetworkRelationLabelRelationDTO>
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSemanticNetworkRelationLabelRelationsForPair", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.semnet.GetSemanticNetworkRelationLabelRelationsForPair")
    @ResponseWrapper(localName = "getSemanticNetworkRelationLabelRelationsForPairResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.semnet.GetSemanticNetworkRelationLabelRelationsForPairResponse")
    public List<SemanticNetworkRelationLabelRelationDTO> getSemanticNetworkRelationLabelRelationsForPair(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "semanticTypeId", targetNamespace = "")
        String semanticTypeId,
        @WebParam(name = "relatedSemanticTypeId", targetNamespace = "")
        String relatedSemanticTypeId)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param semanticGroup
     * @param ticket
     * @param version
     * @return
     *     returns gov.nih.nlm.uts.webservice.semnet.SemanticTypeGroupDTO
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSemanticTypeGroup", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.semnet.GetSemanticTypeGroup")
    @ResponseWrapper(localName = "getSemanticTypeGroupResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.semnet.GetSemanticTypeGroupResponse")
    public SemanticTypeGroupDTO getSemanticTypeGroup(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "semanticGroup", targetNamespace = "")
        String semanticGroup)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param semanticTypeId
     * @param relatedSemanticTypeId
     * @param ticket
     * @param version
     * @return
     *     returns java.util.List<gov.nih.nlm.uts.webservice.semnet.SemanticTypeRelationDTO>
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSemanticTypeRelationsForPair", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.semnet.GetSemanticTypeRelationsForPair")
    @ResponseWrapper(localName = "getSemanticTypeRelationsForPairResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.semnet.GetSemanticTypeRelationsForPairResponse")
    public List<SemanticTypeRelationDTO> getSemanticTypeRelationsForPair(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "semanticTypeId", targetNamespace = "")
        String semanticTypeId,
        @WebParam(name = "relatedSemanticTypeId", targetNamespace = "")
        String relatedSemanticTypeId)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param semanticTypeId
     * @param semanticRelationLabelId
     * @param relatedSemanticTypeId
     * @param ticket
     * @param version
     * @return
     *     returns gov.nih.nlm.uts.webservice.semnet.SemanticTypeRelationDTO
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSemanticTypeRelation", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.semnet.GetSemanticTypeRelation")
    @ResponseWrapper(localName = "getSemanticTypeRelationResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.semnet.GetSemanticTypeRelationResponse")
    public SemanticTypeRelationDTO getSemanticTypeRelation(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "semanticTypeId", targetNamespace = "")
        String semanticTypeId,
        @WebParam(name = "semanticRelationLabelId", targetNamespace = "")
        String semanticRelationLabelId,
        @WebParam(name = "relatedSemanticTypeId", targetNamespace = "")
        String relatedSemanticTypeId)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param semanticTypeId
     * @param ticket
     * @param version
     * @return
     *     returns java.util.List<gov.nih.nlm.uts.webservice.semnet.SemanticTypeRelationDTO>
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSemanticTypeRelations", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.semnet.GetSemanticTypeRelations")
    @ResponseWrapper(localName = "getSemanticTypeRelationsResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.semnet.GetSemanticTypeRelationsResponse")
    public List<SemanticTypeRelationDTO> getSemanticTypeRelations(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "semanticTypeId", targetNamespace = "")
        String semanticTypeId)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param semanticGroup
     * @param ticket
     * @param version
     * @return
     *     returns java.util.List<gov.nih.nlm.uts.webservice.semnet.SemanticTypeDTO>
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSemanticTypesByGroup", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.semnet.GetSemanticTypesByGroup")
    @ResponseWrapper(localName = "getSemanticTypesByGroupResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.semnet.GetSemanticTypesByGroupResponse")
    public List<SemanticTypeDTO> getSemanticTypesByGroup(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "semanticGroup", targetNamespace = "")
        String semanticGroup)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @param version
     * @return
     *     returns java.util.List<gov.nih.nlm.uts.webservice.semnet.SemanticNetworkRelationLabelRelationDTO>
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllSemanticNetworkRelationLabelRelations", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.semnet.GetAllSemanticNetworkRelationLabelRelations")
    @ResponseWrapper(localName = "getAllSemanticNetworkRelationLabelRelationsResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.semnet.GetAllSemanticNetworkRelationLabelRelationsResponse")
    public List<SemanticNetworkRelationLabelRelationDTO> getAllSemanticNetworkRelationLabelRelations(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @param version
     * @return
     *     returns java.util.List<gov.nih.nlm.uts.webservice.semnet.SemanticNetworkRelationLabelDTO>
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllSemanticNetworkRelationLabels", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.semnet.GetAllSemanticNetworkRelationLabels")
    @ResponseWrapper(localName = "getAllSemanticNetworkRelationLabelsResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.semnet.GetAllSemanticNetworkRelationLabelsResponse")
    public List<SemanticNetworkRelationLabelDTO> getAllSemanticNetworkRelationLabels(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @param version
     * @return
     *     returns java.util.List<gov.nih.nlm.uts.webservice.semnet.SemanticTypeGroupDTO>
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllSemanticTypeGroups", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.semnet.GetAllSemanticTypeGroups")
    @ResponseWrapper(localName = "getAllSemanticTypeGroupsResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.semnet.GetAllSemanticTypeGroupsResponse")
    public List<SemanticTypeGroupDTO> getAllSemanticTypeGroups(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @param version
     * @return
     *     returns java.util.List<gov.nih.nlm.uts.webservice.semnet.SemanticTypeDTO>
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllSemanticTypes", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.semnet.GetAllSemanticTypes")
    @ResponseWrapper(localName = "getAllSemanticTypesResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.semnet.GetAllSemanticTypesResponse")
    public List<SemanticTypeDTO> getAllSemanticTypes(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version)
        throws UtsFault_Exception
    ;

}
